const keys=['title','intro','area','length','width','paving','pattern','color','accent','rotation','curbs','garden','sidewalk','front','right','back','left','estimate','waste','tileRate','curbRate','total','export','note','cuts','pieces','curbLength','source','hint','stack','running','herringbone','basket','checker','grey','charcoal','red','brown','sand','white','noir','top','perspective','error','purchase','unitRate','item','quantity'];
const en=['Pavement designer','Design a terrace, path or courtyard.','Rectangle','Length','Width','Paving stones','Laying pattern','Colour','Accent colour','Direction','Curbs','Garden edging','Sidewalk curb','Front','Right','Back','Left','Materials & pricing','Spare allowance (%)','Paving (RON / m²)','Curbs (RON / piece)','Estimated materials','Download BOM (CSV)','Editable demo prices in RON, not a supplier quotation. Excludes VAT, labour, delivery, bedding and foundations. Whole pieces; cut-offs are not reused. Spare allowance applies to paving only.','Cut pieces','Installed pieces','Curb run','View WISE reference','Drag to orbit · scroll to zoom','Straight grid','Running bond','Herringbone','Basket weave','Checkerboard','Grey','Charcoal','Red','Brown','Sand','White','Grey mix','Top view','Perspective','3D preview unavailable. Check WebGL support and reload; the materials estimate is still available.','Purchase area','Unit price','Item','Quantity'];
const ro=['Configurator pavaje','Amenajează o terasă, o alee sau o curte.','Dreptunghi','Lungime','Lățime','Pavele','Model de montaj','Culoare','Culoare secundară','Direcție','Borduri','Bordură de grădină','Bordură de trotuar','Față','Dreapta','Spate','Stânga','Materiale și prețuri','Rezervă (%)','Pavaj (RON / m²)','Borduri (RON / bucată)','Total estimat materiale','Descarcă necesarul (CSV)','Prețuri demonstrative editabile în RON, nu ofertă de furnizor. Fără TVA, manoperă, transport, pat de nisip și fundație. Bucăți întregi; resturile tăiate nu se reutilizează. Rezerva se aplică doar pavelelor.','Bucăți tăiate','Bucăți montate','Lungime borduri','Vezi referința WISE','Trage pentru rotire · derulează pentru zoom','Rosturi aliniate','Rosturi decalate','Spic','Țesut','Tablă de șah','Gri','Antracit','Roșu','Maro','Nisip','Alb','Mix gri','Vedere de sus','Perspectivă','Previzualizare 3D indisponibilă. Verifică suportul WebGL și reîncarcă; estimarea materialelor rămâne disponibilă.','Suprafață de cumpărat','Preț unitar','Articol','Cantitate'];
const de=['Pflasterplaner','Gestalten Sie eine Terrasse, einen Weg oder Hof.','Rechteck','Länge','Breite','Pflastersteine','Verlegemuster','Farbe','Akzentfarbe','Richtung','Randsteine','Gartenrandstein','Gehwegrandstein','Vorne','Rechts','Hinten','Links','Material & Preise','Reserve (%)','Pflaster (RON / m²)','Randsteine (RON / Stück)','Geschätztes Material','Stückliste herunterladen (CSV)','Editierbare Beispielpreise in RON, kein Lieferantenangebot. Ohne MwSt., Arbeit, Lieferung, Bettung und Fundament. Ganze Steine; Zuschnitte werden nicht wiederverwendet. Reserve nur für Pflaster.','Zuschnitte','Verlegte Steine','Randsteinlänge','WISE-Referenz ansehen','Ziehen zum Drehen · Scrollen zum Zoomen','Kreuzfuge','Läuferverband','Fischgrät','Flechtverband','Schachbrett','Grau','Anthrazit','Rot','Braun','Sand','Weiß','Graumix','Draufsicht','Perspektive','3D-Vorschau nicht verfügbar. WebGL prüfen und neu laden; die Materialberechnung bleibt verfügbar.','Bestellfläche','Einzelpreis','Artikel','Menge'];
const areaCopy = {
 en: {area:'Area & dimensions',shape:'Area shape',rectangle:'Rectangle',closed4:'Custom · 4 sides',closed5:'Custom · 5 sides',angleB:'Angle at B',calculated:'calculated',perimeter:'Perimeter',help4:'AB, BC and CD are editable. CD stays parallel to AB; DA closes automatically.',help5:'AB, BC, CD and DE are editable. Corners C and D use 72° exterior turns; EA closes automatically.',invalidArea:'These dimensions cross or collapse the outline, or create a degenerate corner. Adjust the sides or angle. Your previous area is kept.'},
 ro: {area:'Formă și dimensiuni',shape:'Forma suprafeței',rectangle:'Dreptunghi',closed4:'Personalizat · 4 laturi',closed5:'Personalizat · 5 laturi',angleB:'Unghiul în B',calculated:'calculată',perimeter:'Perimetru',help4:'AB, BC și CD sunt editabile. CD rămâne paralelă cu AB; DA închide automat conturul.',help5:'AB, BC, CD și DE sunt editabile. În C și D se folosesc unghiuri exterioare de 72°; EA închide automat conturul.',invalidArea:'Dimensiunile intersectează sau aplatizează conturul, ori creează un colț degenerat. Ajustează laturile sau unghiul. Suprafața anterioară se păstrează.'},
 de: {area:'Form & Maße',shape:'Flächenform',rectangle:'Rechteck',closed4:'Individuell · 4 Seiten',closed5:'Individuell · 5 Seiten',angleB:'Winkel bei B',calculated:'berechnet',perimeter:'Umfang',help4:'AB, BC und CD sind einstellbar. CD bleibt parallel zu AB; DA schließt automatisch.',help5:'AB, BC, CD und DE sind einstellbar. C und D haben Außenwinkel von 72°; EA schließt automatisch.',invalidArea:'Diese Maße ergeben einen gekreuzten oder flachen Umriss oder eine entartete Ecke. Seiten oder Winkel anpassen. Die vorherige Fläche bleibt erhalten.'}
};
const houseCopy={
 en:{house:'House',houseEnabled:'Add a house',houseShape:'Footprint',lShape:'L shape',houseLength:'House length',houseWidth:'House depth',houseWingWidth:'Vertical wing width',houseWingDepth:'Horizontal wing depth',houseHeight:'House height',houseX:'Position X',houseZ:'Position Z',centerHouse:'Centre house in area',houseArea:'House overlap',netArea:'Paved area',grossArea:'Total area',houseHelp:'Drag the house to move it, or use X/Z from the area’s bounding-box origin. Only the overlap with the area is excluded from paving. House geometry is illustrative and is not priced.'},
 ro:{house:'Casă',houseEnabled:'Adaugă o casă',houseShape:'Amprentă',lShape:'Formă L',houseLength:'Lungime casă',houseWidth:'Adâncime casă',houseWingWidth:'Lățime aripă verticală',houseWingDepth:'Adâncime aripă orizontală',houseHeight:'Înălțime casă',houseX:'Poziție X',houseZ:'Poziție Z',centerHouse:'Centrează casa în suprafață',houseArea:'Suprafață ocupată',netArea:'Suprafață pavată',grossArea:'Suprafață totală',houseHelp:'Trage casa pentru a o muta sau folosește X/Z față de originea dreptunghiului ce încadrează terenul. Se scade doar suprapunerea cu terenul. Casa este ilustrativă și nu este inclusă în preț.'},
 de:{house:'Haus',houseEnabled:'Haus hinzufügen',houseShape:'Grundriss',lShape:'L-Form',houseLength:'Hauslänge',houseWidth:'Haustiefe',houseWingWidth:'Breite des vertikalen Flügels',houseWingDepth:'Tiefe des horizontalen Flügels',houseHeight:'Haushöhe',houseX:'Position X',houseZ:'Position Z',centerHouse:'Haus auf der Fläche zentrieren',houseArea:'Hausüberdeckung',netArea:'Pflasterfläche',grossArea:'Gesamtfläche',houseHelp:'Haus ziehen oder X/Z ab dem Ursprung des umschließenden Rechtecks verwenden. Nur die Überdeckung wird von der Pflasterfläche abgezogen. Das Haus ist illustrativ und nicht eingepreist.'}
};
export function translator(locale='en-US'){const values=locale.startsWith('ro')?ro:locale.startsWith('de')?de:en;const dict=Object.fromEntries(keys.map((key,i)=>[key,values[i]]));Object.assign(dict,areaCopy[locale.split('-')[0]]||areaCopy.en,houseCopy[locale.split('-')[0]]||houseCopy.en);return key=>dict[key]||key;}
