import type { ConfiguratorSlug } from "./configurators";
import type { Locale } from "./i18n";
import { pergolaSeoContent, type ConfiguratorSeoContent } from "./pergola-seo-content";

const roofSeoContent: Record<Locale, ConfiguratorSeoContent> = {
  en: {
    intro: {
      label: "3D roof planning",
      heading: "Configure the roof before quantities are rebuilt by hand.",
      body: "The 360Configurator roof tool links roof form, dimensions, pitch and covering choices to one measurable 3D model. Move between standard roof families, change the geometry and inspect the resulting construction quantities instead of treating the visual model and the bill of materials as separate tasks.",
      launch: "Open the 3D roof configurator",
      learn: "See how it works",
    },
    workflow: {
      label: "How it works",
      heading: "From roof shape to measurable output in five steps.",
      intro: "The workflow keeps geometry and quantity logic connected. A dimensional change rebuilds the roof first, then the construction outputs follow the same state.",
      steps: [
        { title: "Choose the roof family", body: "Start from a two-slope, four-slope, single-slope, L-shaped or dormer roof, depending on the architectural condition you need to explore." },
        { title: "Set dimensions and pitch", body: "Adjust length, depth, wall height, roof pitch and eaves overhang while the envelope rebuilds in real time." },
        { title: "Select the covering system", body: "Apply the available metal or mineral covering preset so the visible roof and the compatible geometric rules remain connected." },
        { title: "Inspect measurable geometry", body: "Review roof area together with ridge, eaves, valley, flashing, gutter and related component lengths derived from the current model." },
        { title: "Continue with BOM and CSV", body: "Use the generated component list for estimating and export the bill of materials as structured CSV when the configuration is ready to leave the visual stage." },
      ],
    },
    decisions: {
      label: "What you can configure",
      heading: "Test the roof decisions that change both form and quantities.",
      intro: "A roof configurator becomes useful when the same geometric decision affects appearance, dimensions and material requirements. These are the decisions the tool keeps together.",
      groups: [
        { title: "Roof geometry", body: "Choose the architectural family before refining dimensions.", items: ["Two-slope roof", "Four-slope roof", "Single-slope roof", "L-shaped roof", "Dormer roof"] },
        { title: "Dimensions & slope", body: "Change the main parameters that define the roof envelope.", items: ["Building length and depth", "Wall height", "Roof pitch", "Eaves overhang", "Live dimension readout"] },
        { title: "Covering & constraints", body: "Connect the visual roof to a material system rather than applying a decorative texture only.", items: ["Metal covering presets", "Mineral covering presets", "Material-aware appearance", "Pitch compatibility rules"] },
        { title: "Quantities & handoff", body: "Use the generated geometry as the source for downstream commercial work.", items: ["Roof area", "Ridges, eaves and valleys", "Flashings and gutters", "Bill of materials", "CSV export"] },
      ],
    },
    outcomes: {
      label: "Why configure in 3D",
      heading: "One roof state for design decisions and estimating.",
      body: "Roof geometry becomes difficult to communicate when dimensions, intersections and quantities live in separate drawings and spreadsheets. Keeping them connected reduces re-entry and makes each change easier to understand.",
      items: [
        { title: "For the customer", body: "Compare roof forms and proportions visually before the project is reduced to a list of dimensions and materials." },
        { title: "For estimating teams", body: "Use measurable geometry as the starting point for quantities instead of manually rebuilding each variant after every design change." },
        { title: "For manufacturers and installers", body: "Carry the configured roof into a component-oriented BOM and structured CSV workflow with fewer disconnected handoffs." },
      ],
    },
    faq: {
      label: "Roof configurator FAQ",
      heading: "Common questions about the 3D roof configurator.",
      items: [
        { question: "Which roof types can I configure?", answer: "The current configurator includes two-slope, four-slope, single-slope, L-shaped and dormer roof families." },
        { question: "Can I change the roof dimensions and pitch?", answer: "Yes. Length, depth, wall height, roof pitch and eaves overhang are configurable and the roof rebuilds as those values change." },
        { question: "Does the configurator support different roof coverings?", answer: "Yes. The current workflow includes metal and mineral covering presets, with the material choice tied to the roof state rather than treated as a separate image." },
        { question: "Can it calculate roof quantities?", answer: "The generated geometry is used to derive roof area and construction lengths such as ridge, eaves, valleys, flashings and gutters, together with associated component quantities." },
        { question: "What if my roof is outside the standard parametric families?", answer: "The project includes a custom-plan intake path for PDF, image, DWG or DXF references so non-standard cases can enter a separate workflow." },
        { question: "Can I export a bill of materials?", answer: "Yes. The current roof configurator exposes component-level BOM data and can export the bill of materials as CSV." },
        { question: "Do I need to install software?", answer: "No. The configurator runs in a modern web browser and uses WebGL for the interactive 3D scene." },
      ],
    },
    finalCta: {
      eyebrow: "Try the actual product",
      heading: "Build and measure a roof configuration in the browser.",
      body: "Open the live roof configurator to test roof families, dimensions, pitch, materials and construction quantities, or contact us if you need the same type of rule-driven workflow for your own roofing system.",
      launch: "Launch roof configurator",
      contact: "Discuss a configurator project",
    },
  },
  ro: {
    intro: {
      label: "Proiectare acoperiș 3D",
      heading: "Configurează acoperișul înainte să refaci manual cantitățile.",
      body: "Configuratorul de acoperișuri 360Configurator leagă forma acoperișului, dimensiunile, panta și învelitoarea de același model 3D măsurabil. Poți schimba tipologia și geometria, apoi verifica suprafețele și lungimile constructive rezultate fără să separi modelul vizual de calculul necesarului.",
      launch: "Deschide configuratorul de acoperiș 3D",
      learn: "Vezi cum funcționează",
    },
    workflow: {
      label: "Cum funcționează",
      heading: "De la forma acoperișului la cantități măsurabile în cinci pași.",
      intro: "Geometria și necesarul rămân conectate. Când schimbi o dimensiune, acoperișul se reconstruiește, iar măsurătorile se actualizează din aceeași configurație.",
      steps: [
        { title: "Alege tipul de acoperiș", body: "Pornește de la un acoperiș în două ape, patru ape, o apă, formă L sau cu lucarnă, în funcție de situația pe care vrei să o configurezi." },
        { title: "Setează dimensiunile și panta", body: "Modifică lungimea, adâncimea, înălțimea pereților, panta și streașina, iar învelitoarea se reconstruiește în timp real." },
        { title: "Alege sistemul de învelitoare", body: "Alege varianta metalică sau minerală disponibilă, astfel încât aspectul și regulile geometrice compatibile să rămână legate de configurație." },
        { title: "Verifică geometria măsurabilă", body: "Urmărește suprafața acoperișului și lungimile de coamă, streașină, dolie, tinichigerie și jgheab rezultate din modelul curent." },
        { title: "Continuă cu BOM și CSV", body: "Folosește lista de componente pentru estimare și exportă BOM-ul în format CSV atunci când configurația este pregătită pentru etapa comercială." },
      ],
    },
    decisions: {
      label: "Ce poți configura",
      heading: "Testează deciziile care schimbă atât forma, cât și necesarul.",
      intro: "La acoperiș, aceeași modificare geometrică influențează aspectul, dimensiunile și cantitățile. Configuratorul păstrează toate aceste rezultate sincronizate.",
      groups: [
        { title: "Geometria acoperișului", body: "Alege tipologia arhitecturală înainte de reglarea dimensiunilor.", items: ["Acoperiș în două ape", "Acoperiș în patru ape", "Acoperiș într-o apă", "Acoperiș în L", "Acoperiș cu lucarnă"] },
        { title: "Dimensiuni și pantă", body: "Modifică parametrii principali ai volumului.", items: ["Lungime și adâncime", "Înălțimea pereților", "Panta acoperișului", "Streașină", "Dimensiuni vizibile în scenă"] },
        { title: "Învelitoare și reguli", body: "Leagă modelul 3D de un sistem de material, nu doar de o textură.", items: ["Învelitoare metalică", "Învelitoare minerală", "Aspect specific materialului", "Reguli de compatibilitate cu panta"] },
        { title: "Cantități și export", body: "Folosește geometria generată ca sursă pentru etapa comercială.", items: ["Suprafață acoperiș", "Coame, streșini și dolii", "Tinichigerii și jgheaburi", "Listă de materiale", "Export CSV"] },
      ],
    },
    outcomes: {
      label: "De ce configurare 3D",
      heading: "Aceeași configurație pentru proiectare și estimare.",
      body: "Un acoperiș devine greu de urmărit atunci când forma, cotele și necesarul sunt păstrate în documente diferite. Legarea lor de același model face mai clar efectul fiecărei modificări și reduce refacerea manuală.",
      items: [
        { title: "Pentru beneficiar", body: "Compară vizual tipuri de acoperiș și proporții înainte ca proiectul să fie redus la cote și liste de materiale." },
        { title: "Pentru ofertare", body: "Pornește calculul cantităților din geometria configurată, fără să reconstruiești manual fiecare variantă după o schimbare." },
        { title: "Pentru producție și montaj", body: "Continuă din configurație către o listă de componente și un export CSV mai ușor de integrat în fluxul tehnic." },
      ],
    },
    faq: {
      label: "Întrebări despre configuratorul de acoperiș",
      heading: "Întrebări frecvente despre configurarea acoperișului 3D.",
      items: [
        { question: "Ce tipuri de acoperiș pot configura?", answer: "Versiunea actuală include acoperiș în două ape, patru ape, o apă, formă L și acoperiș cu lucarnă." },
        { question: "Pot modifica dimensiunile și panta acoperișului?", answer: "Da. Lungimea, adâncimea, înălțimea pereților, panta și streașina sunt configurabile, iar geometria se reconstruiește pe măsură ce valorile se schimbă." },
        { question: "Pot selecta tipul de învelitoare?", answer: "Da. Fluxul actual include preseturi pentru învelitori metalice și minerale, iar alegerea materialului rămâne legată de starea acoperișului." },
        { question: "Configuratorul calculează suprafața și lungimile acoperișului?", answer: "Modelul generat este folosit pentru suprafață și pentru lungimi constructive precum coama, streașina, doliile, tinichigeriile și jgheaburile." },
        { question: "Ce fac dacă acoperișul meu nu intră în tipologiile standard?", answer: "Proiectul include un flux separat de preluare a planurilor PDF, imagine, DWG sau DXF pentru cazurile care ies din familiile parametrice standard." },
        { question: "Pot exporta un necesar de materiale?", answer: "Da. Configuratorul oferă date BOM la nivel de componente și permite exportul listei de materiale în CSV." },
        { question: "Trebuie instalat un program?", answer: "Nu. Configuratorul rulează într-un browser modern și folosește WebGL pentru scena 3D interactivă." },
      ],
    },
    finalCta: {
      eyebrow: "Testează produsul",
      heading: "Construiește și măsoară un acoperiș direct în browser.",
      body: "Deschide configuratorul pentru a testa tipologiile, dimensiunile, panta, materialele și cantitățile sau discută cu noi dacă ai nevoie de un flux similar pentru propriul sistem de acoperiș.",
      launch: "Deschide configuratorul de acoperiș",
      contact: "Discută un proiect de configurator",
    },
  },
  de: {
    intro: {
      label: "3D Dachplanung",
      heading: "Konfigurieren Sie das Dach, bevor Mengen manuell neu berechnet werden.",
      body: "Der 360Configurator Dach-Konfigurator verbindet Dachform, Maße, Neigung und Deckung mit einem messbaren 3D-Modell. Wechseln Sie zwischen Dachfamilien, verändern Sie die Geometrie und prüfen Sie daraus abgeleitete Konstruktionsmengen, ohne Visualisierung und Stückliste getrennt aufzubauen.",
      launch: "3D Dach-Konfigurator öffnen",
      learn: "So funktioniert es",
    },
    workflow: {
      label: "So funktioniert es",
      heading: "Von der Dachform zu messbaren Ergebnissen in fünf Schritten.",
      intro: "Geometrie und Mengenlogik bleiben miteinander verbunden. Eine Maßänderung baut zuerst das Dach neu auf; die konstruktiven Ausgaben folgen demselben Zustand.",
      steps: [
        { title: "Dachfamilie wählen", body: "Starten Sie mit Sattel-, Walm-, Pult-, L-förmigem oder Gaubendach, passend zur architektonischen Situation." },
        { title: "Maße und Neigung einstellen", body: "Ändern Sie Länge, Tiefe, Wandhöhe, Dachneigung und Traufüberstand, während die Hülle in Echtzeit neu entsteht." },
        { title: "Deckungssystem auswählen", body: "Wenden Sie einen verfügbaren Metall- oder Mineral-Preset an, damit Erscheinung und kompatible Geometrieregeln Teil derselben Konfiguration bleiben." },
        { title: "Messbare Geometrie prüfen", body: "Prüfen Sie Dachfläche sowie First-, Trauf-, Kehl-, Anschluss- und Rinnenlängen, die aus dem aktuellen Modell abgeleitet werden." },
        { title: "Mit Stückliste und CSV weiterarbeiten", body: "Nutzen Sie die Komponentenliste für die Kalkulation und exportieren Sie die Stückliste als strukturierte CSV-Datei." },
      ],
    },
    decisions: {
      label: "Was Sie konfigurieren können",
      heading: "Testen Sie Entscheidungen, die Form und Mengen gleichzeitig verändern.",
      intro: "Beim Dach beeinflusst dieselbe geometrische Entscheidung Erscheinung, Maße und Materialbedarf. Der Konfigurator hält diese Auswirkungen in einem Modell zusammen.",
      groups: [
        { title: "Dachgeometrie", body: "Wählen Sie die architektonische Grundform vor der Feinabstimmung.", items: ["Satteldach", "Walmdach", "Pultdach", "L-förmiges Dach", "Gaubendach"] },
        { title: "Maße & Neigung", body: "Verändern Sie die Hauptparameter der Dachhülle.", items: ["Gebäudelänge und -tiefe", "Wandhöhe", "Dachneigung", "Traufüberstand", "Sichtbare Maße in der 3D-Szene"] },
        { title: "Deckung & Regeln", body: "Verbinden Sie das 3D-Modell mit einem Materialsystem statt nur mit einer Oberfläche.", items: ["Metallische Deckungspresets", "Mineralische Deckungspresets", "Materialgerechte Darstellung", "Neigungsbezogene Kompatibilitätsregeln"] },
        { title: "Mengen & Übergabe", body: "Verwenden Sie die generierte Geometrie als Quelle für die kaufmännische Weiterverarbeitung.", items: ["Dachfläche", "Firste, Traufen und Kehlen", "Anschlüsse und Rinnen", "Stückliste", "CSV-Export"] },
      ],
    },
    outcomes: {
      label: "Warum 3D konfigurieren",
      heading: "Ein Dachzustand für Planung und Kalkulation.",
      body: "Dachprojekte werden schwer nachvollziehbar, wenn Form, Maße und Mengen in getrennten Zeichnungen und Tabellen geführt werden. Ein gemeinsamer Modellzustand macht Änderungen verständlicher und reduziert manuelle Neuerfassung.",
      items: [
        { title: "Für Bauherren", body: "Vergleichen Sie Dachformen und Proportionen visuell, bevor das Projekt auf Maße und Materiallisten reduziert wird." },
        { title: "Für Kalkulationsteams", body: "Nutzen Sie messbare Geometrie als Ausgangspunkt für Mengen, statt jede Variante nach einer Änderung erneut aufzubauen." },
        { title: "Für Hersteller und Montage", body: "Überführen Sie die konfigurierte Geometrie in eine komponentenorientierte Stückliste und strukturierte CSV-Daten." },
      ],
    },
    faq: {
      label: "Dach-Konfigurator FAQ",
      heading: "Häufige Fragen zum 3D Dach-Konfigurator.",
      items: [
        { question: "Welche Dachformen kann ich konfigurieren?", answer: "Der aktuelle Konfigurator umfasst Sattel-, Walm-, Pult-, L-förmige und Gaubendächer." },
        { question: "Kann ich Maße und Dachneigung verändern?", answer: "Ja. Länge, Tiefe, Wandhöhe, Dachneigung und Traufüberstand sind konfigurierbar und die Geometrie baut sich bei Änderungen neu auf." },
        { question: "Kann ich verschiedene Deckungssysteme wählen?", answer: "Ja. Der aktuelle Ablauf enthält Presets für metallische und mineralische Deckungen, die mit dem Dachzustand verbunden bleiben." },
        { question: "Berechnet der Konfigurator Dachmengen?", answer: "Die generierte Geometrie dient zur Ableitung von Dachfläche sowie konstruktiven Längen wie First, Traufe, Kehlen, Anschlüssen und Rinnen." },
        { question: "Was passiert bei einem Dach außerhalb der Standardfamilien?", answer: "Für nicht standardisierte Fälle enthält das Projekt einen separaten Plan-Intake für PDF-, Bild-, DWG- oder DXF-Referenzen." },
        { question: "Kann ich eine Stückliste exportieren?", answer: "Ja. Der aktuelle Dach-Konfigurator stellt komponentenbezogene BOM-Daten bereit und kann die Stückliste als CSV exportieren." },
        { question: "Muss Software installiert werden?", answer: "Nein. Der Konfigurator läuft in einem modernen Webbrowser und verwendet WebGL für die interaktive 3D-Darstellung." },
      ],
    },
    finalCta: {
      eyebrow: "Produkt direkt testen",
      heading: "Konfigurieren und messen Sie ein Dach direkt im Browser.",
      body: "Öffnen Sie den Dach-Konfigurator, um Dachformen, Maße, Neigung, Materialien und Mengen selbst zu testen, oder sprechen Sie mit uns über einen ähnlichen Workflow für Ihr eigenes Dachsystem.",
      launch: "Dach-Konfigurator starten",
      contact: "Konfigurator-Projekt besprechen",
    },
  },
};

const windowSeoContent: Record<Locale, ConfiguratorSeoContent> = {
  en: {
    intro: {
      label: "3D window configuration",
      heading: "Configure the window as a technical assembly, not a flat catalogue image.",
      body: "The 360Configurator window tool keeps dimensions, profile geometry, glazing, seals, glazing beads, opening behavior and finishes in the same interactive product state. The result is useful when a window system needs to be explained as an engineered assembly rather than reduced to width, height and color.",
      launch: "Open the 3D window configurator",
      learn: "See how it works",
    },
    workflow: {
      label: "How it works",
      heading: "From layout to technical inspection in five steps.",
      intro: "The window stays connected to its underlying system logic as the configuration changes, including multi-cell layouts where the current layout tool supports them.",
      steps: [
        { title: "Set the window layout and size", body: "Choose the current cell arrangement and adjust the overall dimensions within the configured system limits." },
        { title: "Resolve the profile and glass stack", body: "Keep frame, sash, glazing, seals and glazing beads connected while glazing thickness and compatible components are evaluated." },
        { title: "Choose opening behavior", body: "Configure fixed or operable cells where available, switch opening mode and inspect sash movement through the 3D scene." },
        { title: "Specify finishes", body: "Use a uniform treatment or separate interior and exterior finishes, including bicolor combinations supported by the current system." },
        { title: "Inspect the assembly", body: "Use assembled, exploded and technical views to understand profile sections, component relationships and the configured construction." },
      ],
    },
    decisions: {
      label: "What you can configure",
      heading: "Make the technical choices visible before the window reaches production.",
      intro: "Profile systems contain dependencies that are difficult to explain in a conventional product form. The configurator exposes those dependencies in the same scene.",
      groups: [
        { title: "Layout & dimensions", body: "Define the visible composition and the size of the current window system.", items: ["Single or multi-cell arrangements", "Fixed and sash cells", "Width and height controls", "Merged layout states where supported"] },
        { title: "Profiles & glazing", body: "Keep the section build-up connected to the selected glass stack.", items: ["Frame and sash profiles", "Glazing thickness", "Compatible gasket codes", "Compatible glazing-bead codes"] },
        { title: "Opening behavior", body: "Inspect how operable parts move rather than describing them only with icons.", items: ["Side-hung operation", "Tilt operation", "Opening-angle control", "3D sash movement"] },
        { title: "Finishes & diagnostics", body: "Combine commercial finish decisions with technical inspection.", items: ["Mill, anodized and powder-coated finishes", "Independent interior/exterior treatment", "Bicolor configuration", "Exploded and profile-section views"] },
      ],
    },
    outcomes: {
      label: "Why configure in 3D",
      heading: "A window system that can be understood before fabrication.",
      body: "A technical window is more than an opening in a wall. Profile relationships, glazing, hardware and finishes interact. Showing them in one configured assembly helps commercial and technical conversations refer to the same product state.",
      items: [
        { title: "For the customer", body: "Understand size, opening behavior and visible finishes without needing to interpret profile drawings first." },
        { title: "For sales and specification", body: "Keep the selected glass stack, compatible components and surface treatment attached to the same visible configuration." },
        { title: "For technical teams", body: "Use exploded and section views to inspect the actual construction logic rather than relying on a generic 3D window model." },
      ],
    },
    faq: {
      label: "Window configurator FAQ",
      heading: "Common questions about the 3D window configurator.",
      items: [
        { question: "Can I change the window dimensions?", answer: "Yes. Width and height are configurable within the limits of the active profile-system setup, and connected elements rebuild with those changes." },
        { question: "Can I configure more than one window cell?", answer: "Yes. The current layout system supports fixed and sash cells in multi-cell arrangements, including supported merge states." },
        { question: "Does glazing thickness affect the configuration?", answer: "Yes. The glass-stack workflow connects glazing thickness to compatible gasket and glazing-bead selections." },
        { question: "Can I simulate how the sash opens?", answer: "Yes. The current configurator supports opening-mode changes and an opening-angle control for inspecting sash movement in 3D." },
        { question: "Can inside and outside finishes be different?", answer: "Yes. The finish workflow supports a uniform treatment or independent interior and exterior treatments, including bicolor states." },
        { question: "Can I inspect the actual profile construction?", answer: "Yes. The configurator includes exploded and technical inspection views that expose profile, seal, glazing and assembly relationships." },
        { question: "Do I need to install software?", answer: "No. The configurator runs in a modern browser and uses WebGL for the interactive 3D model." },
      ],
    },
    finalCta: {
      eyebrow: "Try the actual product",
      heading: "Configure a technical window assembly in the browser.",
      body: "Open the live window configurator to test layout, dimensions, glazing, opening behavior, finishes and technical views, or contact us if you need a configurator for another architectural profile system.",
      launch: "Launch window configurator",
      contact: "Discuss a configurator project",
    },
  },
  ro: {
    intro: {
      label: "Configurare ferestre 3D",
      heading: "Configurează fereastra ca ansamblu tehnic, nu ca imagine de catalog.",
      body: "Configuratorul de ferestre păstrează împreună dimensiunile, profilele, vitrajul, garniturile, baghetele, modul de deschidere și finisajele. Astfel, clientul poate înțelege produsul tehnic complet, nu doar lățimea, înălțimea și culoarea.",
      launch: "Deschide configuratorul de ferestre 3D",
      learn: "Vezi cum funcționează",
    },
    workflow: {
      label: "Cum funcționează",
      heading: "De la compartimentare la inspecția tehnică în cinci pași.",
      intro: "Fereastra rămâne legată de logica sistemului de profile pe măsură ce configurația se schimbă, inclusiv în compozițiile cu mai multe celule acceptate de instrumentul actual.",
      steps: [
        { title: "Stabilește compartimentarea și dimensiunile", body: "Alege aranjamentul curent al celulelor și modifică dimensiunile generale în limitele sistemului configurat." },
        { title: "Alege profilele și pachetul de sticlă", body: "Tocul, cerceveaua, vitrajul, garniturile și baghetele se actualizează împreună când schimbi grosimea sticlei sau componentele compatibile." },
        { title: "Alege modul de deschidere", body: "Configurează celule fixe sau mobile unde sunt disponibile, schimbă tipul de deschidere și urmărește mișcarea cercevelei în modelul 3D." },
        { title: "Specifică finisajele", body: "Folosește același finisaj sau tratamente diferite la interior și exterior, inclusiv configurații bicolore acceptate de sistem." },
        { title: "Inspectează ansamblul", body: "Folosește vederea montată, explodată și modurile tehnice pentru a înțelege secțiunile de profil și relațiile dintre componente." },
      ],
    },
    decisions: {
      label: "Ce poți configura",
      heading: "Fă vizibile deciziile tehnice înainte ca fereastra să ajungă în producție.",
      intro: "Componentele unui sistem de profile depind unele de altele și sunt greu de explicat într-un formular. Configuratorul le păstrează împreună în același model 3D.",
      groups: [
        { title: "Compartimentare și dimensiuni", body: "Definește compoziția vizibilă și mărimea ansamblului.", items: ["Configurații cu una sau mai multe celule", "Celule fixe și cercevele", "Controlul lățimii și înălțimii", "Stări de îmbinare acolo unde sunt acceptate"] },
        { title: "Profile și vitraj", body: "Leagă secțiunea tehnică de pachetul de sticlă selectat.", items: ["Profile de cadru și cercevea", "Grosimea vitrajului", "Coduri compatibile de garnituri", "Coduri compatibile de baghete"] },
        { title: "Modul de deschidere", body: "Urmărește direct mișcarea elementelor mobile.", items: ["Deschidere batantă", "Deschidere oscilo-batantă", "Controlul unghiului de deschidere", "Mișcarea 3D a cercevelei"] },
        { title: "Finisaje și diagnostic", body: "Combină alegerea comercială a finisajului cu inspecția tehnică.", items: ["Finisaj brut, anodizat sau vopsit", "Tratamente independente interior/exterior", "Configurație bicoloră", "Vedere explodată și secțiuni de profil"] },
      ],
    },
    outcomes: {
      label: "De ce configurare 3D",
      heading: "Un sistem de fereastră care poate fi înțeles înainte de fabricație.",
      body: "O fereastră tehnică înseamnă mai mult decât un gol în perete. Profilele, vitrajul, feroneria și finisajele se influențează reciproc. Un singur ansamblu configurat ajută discuția comercială și tehnică să se refere la același produs.",
      items: [
        { title: "Pentru beneficiar", body: "Înțelege dimensiunea, modul de deschidere și finisajele vizibile fără să interpreteze mai întâi desene de profil." },
        { title: "Pentru vânzare și specificație", body: "Păstrează pachetul de sticlă, componentele compatibile și tratamentul suprafeței legate de aceeași configurație." },
        { title: "Pentru echipa tehnică", body: "Folosește vederea explodată și secțiunile pentru a verifica logica reală de construcție, nu un model generic de fereastră." },
      ],
    },
    faq: {
      label: "Întrebări despre configuratorul de ferestre",
      heading: "Întrebări frecvente despre configurarea ferestrelor 3D.",
      items: [
        { question: "Pot modifica dimensiunile ferestrei?", answer: "Da. Lățimea și înălțimea sunt configurabile în limitele sistemului activ, iar elementele conectate se reconstruiesc împreună." },
        { question: "Pot configura mai multe celule de fereastră?", answer: "Da. Sistemul actual de layout permite celule fixe și cercevele în compoziții cu mai multe celule, inclusiv stări de îmbinare acceptate." },
        { question: "Grosimea sticlei influențează configurația?", answer: "Da. Fluxul de vitraj leagă grosimea pachetului de sticlă de garniturile și baghetele compatibile." },
        { question: "Pot simula deschiderea cercevelei?", answer: "Da. Configuratorul permite schimbarea modului de deschidere și controlul unghiului pentru a inspecta mișcarea în 3D." },
        { question: "Pot avea finisaje diferite la interior și exterior?", answer: "Da. Poți folosi același tratament sau finisaje independente pentru interior și exterior, inclusiv configurații bicolore." },
        { question: "Pot vedea construcția reală a profilului?", answer: "Da. Configuratorul include vederi explodate și tehnice care expun relațiile dintre profil, garnituri, vitraj și ansamblu." },
        { question: "Trebuie instalat un program?", answer: "Nu. Configuratorul rulează într-un browser modern și folosește WebGL pentru modelul 3D interactiv." },
      ],
    },
    finalCta: {
      eyebrow: "Testează produsul",
      heading: "Configurează un ansamblu de fereastră tehnică direct în browser.",
      body: "Deschide configuratorul pentru a testa compartimentarea, dimensiunile, vitrajul, deschiderea, finisajele și vederile tehnice sau discută cu noi despre un configurator pentru alt sistem de profile.",
      launch: "Deschide configuratorul de ferestre",
      contact: "Discută un proiect de configurator",
    },
  },
  de: {
    intro: {
      label: "3D Fensterkonfiguration",
      heading: "Konfigurieren Sie das Fenster als technische Baugruppe, nicht als Katalogbild.",
      body: "Der 360Configurator Fenster-Konfigurator hält Maße, Profilgeometrie, Verglasung, Dichtungen, Glasleisten, Öffnungsverhalten und Oberflächen in einem interaktiven Produktzustand zusammen. Das ist hilfreich, wenn ein Fenstersystem als technische Baugruppe erklärt werden muss und nicht nur über Breite, Höhe und Farbe.",
      launch: "3D Fenster-Konfigurator öffnen",
      learn: "So funktioniert es",
    },
    workflow: {
      label: "So funktioniert es",
      heading: "Von der Aufteilung zur technischen Prüfung in fünf Schritten.",
      intro: "Das Fenster bleibt bei Änderungen mit der Logik des Profilsystems verbunden, einschließlich mehrteiliger Anordnungen, soweit sie vom aktuellen Layout-Werkzeug unterstützt werden.",
      steps: [
        { title: "Aufteilung und Maße festlegen", body: "Wählen Sie die aktuelle Zellanordnung und verändern Sie die Gesamtmaße innerhalb der hinterlegten Systemgrenzen." },
        { title: "Profil und Glasaufbau abstimmen", body: "Halten Sie Rahmen, Flügel, Verglasung, Dichtungen und Glasleisten verbunden, während Glasstärke und kompatible Komponenten bewertet werden." },
        { title: "Öffnungsverhalten wählen", body: "Konfigurieren Sie feste oder öffenbare Felder, soweit verfügbar, und prüfen Sie die Flügelbewegung direkt in der 3D-Szene." },
        { title: "Oberflächen festlegen", body: "Verwenden Sie eine einheitliche Behandlung oder getrennte Innen- und Außenoberflächen einschließlich unterstützter Bicolor-Kombinationen." },
        { title: "Baugruppe untersuchen", body: "Nutzen Sie montierte, explodierte und technische Ansichten, um Profilquerschnitte und Komponentenbeziehungen zu verstehen." },
      ],
    },
    decisions: {
      label: "Was Sie konfigurieren können",
      heading: "Machen Sie technische Entscheidungen vor der Fertigung sichtbar.",
      intro: "Profilsysteme enthalten Abhängigkeiten, die in einem klassischen Produktformular schwer zu erklären sind. Der Konfigurator zeigt sie in derselben Szene.",
      groups: [
        { title: "Aufteilung & Maße", body: "Definieren Sie die sichtbare Komposition und Größe des Fenstersystems.", items: ["Ein- oder mehrteilige Anordnungen", "Feste und Flügelfelder", "Breiten- und Höhensteuerung", "Unterstützte verbundene Layoutzustände"] },
        { title: "Profile & Verglasung", body: "Verbinden Sie den technischen Querschnitt mit dem gewählten Glasaufbau.", items: ["Rahmen- und Flügelprofile", "Glasstärke", "Kompatible Dichtungscodes", "Kompatible Glasleistencodes"] },
        { title: "Öffnungsverhalten", body: "Prüfen Sie die Bewegung öffenbarer Teile statt sie nur mit Symbolen zu beschreiben.", items: ["Drehöffnung", "Kippöffnung", "Öffnungswinkel", "3D-Flügelbewegung"] },
        { title: "Oberflächen & Diagnose", body: "Kombinieren Sie kaufmännische Oberflächenwahl mit technischer Prüfung.", items: ["Roh-, Eloxal- und Pulverbeschichtungszustände", "Getrennte Innen-/Außenbehandlung", "Bicolor-Konfiguration", "Explosions- und Profilansichten"] },
      ],
    },
    outcomes: {
      label: "Warum 3D konfigurieren",
      heading: "Ein Fenstersystem, das vor der Fertigung verständlich wird.",
      body: "Ein technisches Fenster besteht aus mehr als einer Öffnung. Profile, Verglasung, Beschläge und Oberflächen beeinflussen sich gegenseitig. Eine konfigurierte Baugruppe schafft eine gemeinsame Grundlage für kaufmännische und technische Gespräche.",
      items: [
        { title: "Für Kunden", body: "Verstehen Sie Größe, Öffnungsverhalten und sichtbare Oberflächen, ohne zuerst Profilzeichnungen lesen zu müssen." },
        { title: "Für Vertrieb und Spezifikation", body: "Halten Sie Glasaufbau, kompatible Komponenten und Oberflächenbehandlung an derselben sichtbaren Konfiguration." },
        { title: "Für Technikteams", body: "Nutzen Sie Explosions- und Querschnittsansichten, um die reale Konstruktionslogik statt eines generischen Fenstermodells zu prüfen." },
      ],
    },
    faq: {
      label: "Fenster-Konfigurator FAQ",
      heading: "Häufige Fragen zum 3D Fenster-Konfigurator.",
      items: [
        { question: "Kann ich die Fenstermaße verändern?", answer: "Ja. Breite und Höhe sind innerhalb der Grenzen des aktiven Profilsystems konfigurierbar und verbundene Elemente bauen sich gemeinsam neu auf." },
        { question: "Kann ich mehrere Fensterfelder konfigurieren?", answer: "Ja. Das aktuelle Layout-System unterstützt feste und Flügelfelder in mehrteiligen Anordnungen einschließlich unterstützter Verbindungszustände." },
        { question: "Beeinflusst die Glasstärke die Konfiguration?", answer: "Ja. Der Glasaufbau verbindet die Glasstärke mit kompatiblen Dichtungs- und Glasleistenauswahlen." },
        { question: "Kann ich die Flügelöffnung simulieren?", answer: "Ja. Der Konfigurator unterstützt Öffnungsmodi und eine Winkelsteuerung zur Prüfung der Flügelbewegung in 3D." },
        { question: "Können Innen- und Außenoberfläche unterschiedlich sein?", answer: "Ja. Es sind einheitliche oder getrennte Innen-/Außenbehandlungen einschließlich Bicolor-Zuständen möglich." },
        { question: "Kann ich den tatsächlichen Profilaufbau ansehen?", answer: "Ja. Explosions- und technische Ansichten zeigen Beziehungen zwischen Profil, Dichtungen, Verglasung und Baugruppe." },
        { question: "Muss Software installiert werden?", answer: "Nein. Der Konfigurator läuft in einem modernen Browser und verwendet WebGL für das interaktive 3D-Modell." },
      ],
    },
    finalCta: {
      eyebrow: "Produkt direkt testen",
      heading: "Konfigurieren Sie eine technische Fensterbaugruppe direkt im Browser.",
      body: "Öffnen Sie den Fenster-Konfigurator, um Aufteilung, Maße, Verglasung, Öffnung, Oberflächen und technische Ansichten zu testen, oder sprechen Sie mit uns über einen Konfigurator für ein anderes Profilsystem.",
      launch: "Fenster-Konfigurator starten",
      contact: "Konfigurator-Projekt besprechen",
    },
  },
};

const hallSeoContent: Record<Locale, ConfiguratorSeoContent> = {
  en: {
    intro: {
      label: "3D industrial hall planning",
      heading: "Configure the building envelope and structure in the same model.",
      body: "The 360Configurator hall tool connects building dimensions, portal-frame spacing, structure duty, cladding and façade openings in one responsive 3D model. Doors and windows can be positioned on the envelope, while invalid overlaps are detected before the configuration moves into a summary or commercial stage.",
      launch: "Open the 3D hall configurator",
      learn: "See how it works",
    },
    workflow: {
      label: "How it works",
      heading: "From hall dimensions to a coordinated building state in five steps.",
      intro: "The workflow keeps the primary structure, secondary system, envelope and access geometry synchronized instead of treating each as an isolated form.",
      steps: [
        { title: "Set the building dimensions", body: "Adjust length, span, eaves height and roof pitch to define the overall industrial volume." },
        { title: "Resolve the structural rhythm", body: "Set the target frame spacing and choose the structure-duty preset while the portal-frame layout follows the building length." },
        { title: "Configure the envelope", body: "Review the cladding and structural layers together, or isolate them when the construction behind the finished hall needs to be understood." },
        { title: "Place doors and windows", body: "Add personnel doors, garage doors and windows to available wall faces, then position and size the openings within the current building geometry." },
        { title: "Validate and review the result", body: "Use overlap validation, the summary and the exploded/technical views to check whether the current hall state is coherent before moving forward." },
      ],
    },
    decisions: {
      label: "What you can configure",
      heading: "Coordinate the decisions that define an industrial hall.",
      intro: "Building dimensions, structural spacing and façade openings interact. The configurator keeps those decisions spatial so conflicts can be seen rather than discovered after handoff.",
      groups: [
        { title: "Building envelope", body: "Define the main industrial volume.", items: ["Building length", "Clear span", "Eaves height", "Roof pitch", "Cladding visibility"] },
        { title: "Structure", body: "Control the rhythm and visual duty of the steel system.", items: ["Portal-frame spacing", "Equal bay resolution", "Light / standard / heavy presets", "Primary and secondary structure views"] },
        { title: "Doors & windows", body: "Configure access and daylight openings directly on the walls.", items: ["Personnel doors", "Garage doors", "Windows", "Position and dimensions", "Wall-specific placement"] },
        { title: "Validation & inspection", body: "Check whether the current building state is usable before summary.", items: ["Opening-overlap detection", "Invalid-state feedback", "Layer visibility", "Technical edges", "Exploded assembly"] },
      ],
    },
    outcomes: {
      label: "Why configure in 3D",
      heading: "A coordinated hall before drawings and quotations diverge.",
      body: "Industrial halls combine repetitive structure with project-specific dimensions and openings. A single spatial state makes the relationship between those systems easier to review and gives the commercial and technical teams a common reference.",
      items: [
        { title: "For the customer", body: "Understand the overall hall proportions, access points and visible envelope before reviewing a technical drawing set." },
        { title: "For sales and planning", body: "Keep hall size, frame spacing and openings synchronized while alternative building states are discussed." },
        { title: "For technical teams", body: "Use layer and exploded views to inspect the primary structure, secondary members and envelope as coordinated parts of one building." },
      ],
    },
    faq: {
      label: "Hall configurator FAQ",
      heading: "Common questions about the 3D industrial hall configurator.",
      items: [
        { question: "Which hall dimensions can I change?", answer: "The current configurator exposes building length, span, eaves height and roof pitch as the main geometric controls." },
        { question: "Can I control frame spacing?", answer: "Yes. A target bay spacing is resolved into a practical frame count and equal bay spacing across the current building length." },
        { question: "Can I add doors and windows?", answer: "Yes. The current opening system includes personnel doors, garage doors and windows that can be positioned on supported wall faces." },
        { question: "Does the configurator detect overlapping openings?", answer: "Yes. The opening system checks overlaps and exposes invalid states so conflicting door/window placement can be corrected." },
        { question: "Can I inspect the structure without the cladding?", answer: "Yes. Envelope and structural layers can be toggled so the portal frames and secondary members can be inspected separately." },
        { question: "Is there an exploded view?", answer: "Yes. The hall can be separated into envelope, secondary steel and primary portal frames, then returned to the assembled state." },
        { question: "Do I need to install software?", answer: "No. The configurator runs in a modern browser and uses WebGL for the interactive 3D model." },
      ],
    },
    finalCta: {
      eyebrow: "Try the actual product",
      heading: "Configure an industrial hall directly in the browser.",
      body: "Open the live hall configurator to test building dimensions, frame spacing, structure, cladding and façade openings, or contact us about a configurator for your own industrial building system.",
      launch: "Launch hall configurator",
      contact: "Discuss a configurator project",
    },
  },
  ro: {
    intro: {
      label: "Proiectare hală industrială 3D",
      heading: "Configurează anvelopa și structura halei în același model.",
      body: "Configuratorul de hale 360Configurator leagă dimensiunile clădirii, distanța dintre cadrele portal, clasa structurală, închiderile și golurile de fațadă într-un singur model 3D. Ușile și ferestrele pot fi poziționate pe anvelopă, iar suprapunerile invalide sunt detectate înainte ca proiectul să continue către rezumat.",
      launch: "Deschide configuratorul de hală 3D",
      learn: "Vezi cum funcționează",
    },
    workflow: {
      label: "Cum funcționează",
      heading: "De la dimensiunile halei la o clădire coordonată în cinci pași.",
      intro: "Structura principală, structura secundară, anvelopa și golurile de acces rămân sincronizate, în loc să fie configurate în formulare independente.",
      steps: [
        { title: "Setează dimensiunile clădirii", body: "Modifică lungimea, deschiderea, înălțimea la streașină și panta acoperișului pentru a defini volumul halei." },
        { title: "Stabilește distanța dintre cadre", body: "Alege distanța dorită și varianta structurală, iar cadrele portal se distribuie automat pe lungimea clădirii." },
        { title: "Configurează anvelopa", body: "Privește închiderile și structura împreună sau izolează straturile atunci când trebuie explicată construcția din spatele halei finite." },
        { title: "Poziționează uși și ferestre", body: "Adaugă uși pietonale, uși de garaj și ferestre pe pereții disponibili, apoi ajustează poziția și dimensiunile lor." },
        { title: "Verifică configurația", body: "Rezolvă suprapunerile și folosește rezumatul, vederile tehnice și vederea explodată înainte de etapa următoare." },
      ],
    },
    decisions: {
      label: "Ce poți configura",
      heading: "Coordonează deciziile care definesc o hală industrială.",
      intro: "Dimensiunile clădirii, structura și golurile de fațadă se influențează reciproc. Configuratorul le arată în același model, astfel încât conflictele să poată fi observate înainte de predare.",
      groups: [
        { title: "Anvelopa clădirii", body: "Definește volumul industrial principal.", items: ["Lungimea halei", "Deschiderea liberă", "Înălțimea la streașină", "Panta acoperișului", "Vizibilitatea închiderilor"] },
        { title: "Structură", body: "Controlează distanța dintre cadre și varianta structurii metalice.", items: ["Distanța dintre cadre portal", "Travei egale", "Structură ușoară, standard sau grea", "Structură principală și secundară"] },
        { title: "Uși și ferestre", body: "Configurează accesul și golurile direct pe pereți.", items: ["Uși pietonale", "Uși de garaj", "Ferestre", "Poziție și dimensiuni", "Amplasare pe fiecare fațadă"] },
        { title: "Verificare și inspecție", body: "Verifică modelul înainte de a genera rezumatul.", items: ["Detectarea suprapunerilor", "Mesaje pentru configurații invalide", "Afișarea separată a componentelor", "Muchii tehnice", "Vedere explodată"] },
      ],
    },
    outcomes: {
      label: "De ce configurare 3D",
      heading: "Aceeași configurație pentru prezentare, verificare și ofertare.",
      body: "O hală industrială combină o structură repetitivă cu dimensiunile și golurile fiecărui proiect. Modelul 3D oferă o referință comună pentru client, vânzări și echipa tehnică.",
      items: [
        { title: "Pentru beneficiar", body: "Înțelege proporțiile halei, punctele de acces și anvelopa înainte de a analiza un set complet de desene tehnice." },
        { title: "Pentru vânzare și planificare", body: "Păstrează dimensiunea halei, ritmul cadrelor și golurile sincronizate atunci când se discută variante." },
        { title: "Pentru echipa tehnică", body: "Folosește straturile și vederea explodată pentru a inspecta cadrele principale, elementele secundare și anvelopa ca părți coordonate." },
      ],
    },
    faq: {
      label: "Întrebări despre configuratorul de hale",
      heading: "Întrebări frecvente despre configurarea unei hale industriale 3D.",
      items: [
        { question: "Ce dimensiuni ale halei pot modifica?", answer: "Configuratorul actual permite modificarea lungimii, deschiderii, înălțimii la streașină și pantei acoperișului." },
        { question: "Pot controla distanța dintre cadre?", answer: "Da. O distanță țintă este transformată într-un număr practic de cadre și travei egale pe lungimea clădirii." },
        { question: "Pot adăuga uși și ferestre?", answer: "Da. Sistemul actual include uși pietonale, uși de garaj și ferestre care pot fi poziționate pe fațadele acceptate." },
        { question: "Configuratorul detectează golurile care se suprapun?", answer: "Da. Sistemul verifică suprapunerile și marchează stările invalide pentru ca poziționarea ușilor și ferestrelor să poată fi corectată." },
        { question: "Pot vedea structura fără închideri?", answer: "Da. Anvelopa și straturile structurale pot fi afișate sau ascunse independent." },
        { question: "Există vedere explodată?", answer: "Da. Hala poate fi separată vizual în anvelopă, structură secundară și cadre portal principale, apoi reasamblată." },
        { question: "Trebuie instalat un program?", answer: "Nu. Configuratorul rulează într-un browser modern și folosește WebGL pentru modelul 3D interactiv." },
      ],
    },
    finalCta: {
      eyebrow: "Testează produsul",
      heading: "Configurează o hală industrială direct în browser.",
      body: "Deschide configuratorul pentru a testa dimensiunile, distanța dintre cadre, structura, închiderile și golurile de fațadă sau discută cu noi despre un configurator pentru propriul sistem de hale.",
      launch: "Deschide configuratorul de hală",
      contact: "Discută un proiect de configurator",
    },
  },
  de: {
    intro: {
      label: "3D Hallenplanung",
      heading: "Konfigurieren Sie Gebäudehülle und Tragwerk im selben Modell.",
      body: "Der 360Configurator Hallen-Konfigurator verbindet Gebäudeabmessungen, Portalrahmenabstand, Tragwerksklasse, Gebäudehülle und Fassadenöffnungen in einem 3D-Modell. Türen und Fenster können auf der Hülle positioniert werden; ungültige Überlappungen werden erkannt, bevor die Konfiguration in die Zusammenfassung übergeht.",
      launch: "3D Hallen-Konfigurator öffnen",
      learn: "So funktioniert es",
    },
    workflow: {
      label: "So funktioniert es",
      heading: "Von Hallenmaßen zu einem koordinierten Gebäudezustand in fünf Schritten.",
      intro: "Primärtragwerk, Sekundärsystem, Gebäudehülle und Zugangsgeometrie bleiben synchron, statt als getrennte Formulare behandelt zu werden.",
      steps: [
        { title: "Gebäudeabmessungen festlegen", body: "Ändern Sie Länge, Spannweite, Traufhöhe und Dachneigung, um das industrielle Gesamtvolumen zu definieren." },
        { title: "Tragwerksraster auflösen", body: "Legen Sie den Zielabstand der Rahmen und den Tragwerkspreset fest; das Portalrahmenraster folgt der Gebäudelänge." },
        { title: "Gebäudehülle konfigurieren", body: "Betrachten Sie Hülle und Tragwerk gemeinsam oder isolieren Sie Ebenen, wenn die Konstruktion hinter der fertigen Halle erklärt werden soll." },
        { title: "Türen und Fenster platzieren", body: "Fügen Sie Personaltüren, Garagentore und Fenster auf verfügbaren Wandflächen hinzu und passen Sie Position und Größe an." },
        { title: "Konfiguration validieren", body: "Nutzen Sie Überlappungsprüfung, Zusammenfassung sowie technische und explodierte Ansichten, um den Hallenzustand vor dem nächsten Schritt zu prüfen." },
      ],
    },
    decisions: {
      label: "Was Sie konfigurieren können",
      heading: "Koordinieren Sie die Entscheidungen, die eine Industriehalle definieren.",
      intro: "Gebäudeabmessungen, Tragwerksraster und Fassadenöffnungen beeinflussen sich gegenseitig. Der Konfigurator hält sie räumlich zusammen, sodass Konflikte sichtbar werden.",
      groups: [
        { title: "Gebäudehülle", body: "Definieren Sie das industrielle Hauptvolumen.", items: ["Gebäudelänge", "Freie Spannweite", "Traufhöhe", "Dachneigung", "Sichtbarkeit der Hülle"] },
        { title: "Tragwerk", body: "Steuern Sie Rhythmus und Tragwerksklasse des Stahlsystems.", items: ["Portalrahmenabstand", "Gleichmäßige Feldaufteilung", "Light / Standard / Heavy Presets", "Primär- und Sekundärtragwerk"] },
        { title: "Türen & Fenster", body: "Konfigurieren Sie Zugang und Öffnungen direkt an den Wänden.", items: ["Personaltüren", "Garagentore", "Fenster", "Position und Abmessungen", "Wandbezogene Platzierung"] },
        { title: "Validierung & Prüfung", body: "Prüfen Sie den aktuellen Zustand vor der Zusammenfassung.", items: ["Überlappungserkennung", "Feedback bei ungültigen Zuständen", "Ebenensichtbarkeit", "Technische Kanten", "Explosionsansicht"] },
      ],
    },
    outcomes: {
      label: "Warum 3D konfigurieren",
      heading: "Eine koordinierte Halle, bevor Zeichnung und Angebot auseinanderlaufen.",
      body: "Industriehallen kombinieren wiederholende Tragwerke mit projektspezifischen Abmessungen und Öffnungen. Ein gemeinsamer räumlicher Zustand macht diese Beziehungen leichter nachvollziehbar.",
      items: [
        { title: "Für Kunden", body: "Verstehen Sie Hallenproportionen, Zugangspunkte und sichtbare Gebäudehülle, bevor ein vollständiger technischer Plansatz geprüft wird." },
        { title: "Für Vertrieb und Planung", body: "Halten Sie Hallengröße, Rahmenraster und Öffnungen synchron, während verschiedene Varianten besprochen werden." },
        { title: "Für Technikteams", body: "Nutzen Sie Ebenen- und Explosionsansichten, um Primärtragwerk, Sekundärglieder und Hülle als koordinierte Gebäudeteile zu prüfen." },
      ],
    },
    faq: {
      label: "Hallen-Konfigurator FAQ",
      heading: "Häufige Fragen zum 3D Hallen-Konfigurator.",
      items: [
        { question: "Welche Hallenmaße kann ich verändern?", answer: "Der aktuelle Konfigurator stellt Gebäudelänge, Spannweite, Traufhöhe und Dachneigung als zentrale Geometrieparameter bereit." },
        { question: "Kann ich den Rahmenabstand steuern?", answer: "Ja. Ein Zielabstand wird in eine praktikable Rahmenzahl und gleichmäßige Feldaufteilung über die Gebäudelänge umgesetzt." },
        { question: "Kann ich Türen und Fenster hinzufügen?", answer: "Ja. Das aktuelle Öffnungssystem umfasst Personaltüren, Garagentore und Fenster, die auf unterstützten Wandflächen positioniert werden können." },
        { question: "Erkennt der Konfigurator überlappende Öffnungen?", answer: "Ja. Das Öffnungssystem prüft Überlappungen und kennzeichnet ungültige Zustände, damit Konflikte korrigiert werden können." },
        { question: "Kann ich das Tragwerk ohne Verkleidung betrachten?", answer: "Ja. Gebäudehülle und Tragwerksebenen können unabhängig ein- und ausgeblendet werden." },
        { question: "Gibt es eine Explosionsansicht?", answer: "Ja. Hülle, Sekundärstahl und primäre Portalrahmen können getrennt dargestellt und anschließend wieder zusammengesetzt werden." },
        { question: "Muss Software installiert werden?", answer: "Nein. Der Konfigurator läuft in einem modernen Browser und verwendet WebGL für das interaktive 3D-Modell." },
      ],
    },
    finalCta: {
      eyebrow: "Produkt direkt testen",
      heading: "Konfigurieren Sie eine Industriehalle direkt im Browser.",
      body: "Öffnen Sie den Hallen-Konfigurator, um Abmessungen, Rahmenabstand, Tragwerk, Hülle und Fassadenöffnungen zu testen, oder sprechen Sie mit uns über einen Konfigurator für Ihr eigenes Hallensystem.",
      launch: "Hallen-Konfigurator starten",
      contact: "Konfigurator-Projekt besprechen",
    },
  },
};

const solarSeoContent: Record<Locale, ConfiguratorSeoContent> = {
  en: {
    intro: {
      label: "3D photovoltaic planning",
      heading: "Configure the roof, PV array and household energy model together.",
      body: "The 360Configurator solar tool connects roof geometry, panel fit, geographic context, sun position, household demand and battery storage in one interactive model. It is designed to show not only how a photovoltaic system sits on the roof, but also how system size and consumption assumptions affect the energy picture.",
      launch: "Open the 3D solar configurator",
      learn: "See how it works",
    },
    workflow: {
      label: "How it works",
      heading: "From location and roof geometry to a daily energy scenario in five steps.",
      intro: "The solar workflow combines spatial fit with energy assumptions so the PV system can be reviewed as both a roof-mounted product and an energy system.",
      steps: [
        { title: "Set the location and orientation", body: "Use the project location and roof-front bearing as the environmental context for sun position and production assumptions." },
        { title: "Configure the roof", body: "Choose the supported roof family and adjust its dimensions and pitch so the available photovoltaic surfaces match the building." },
        { title: "Fit the PV array", body: "Choose the requested module count and roof plane; the configurator arranges residential-size modules on the usable roof surface." },
        { title: "Model demand and storage", body: "Select a household consumption profile and enable or size LiFePO₄ battery storage to compare how solar production is used through the day." },
        { title: "Review the energy result", body: "Inspect installed kWp, production, household demand, self-sufficiency, grid import/export and the daily production-versus-consumption profile." },
      ],
    },
    decisions: {
      label: "What you can configure",
      heading: "Connect the physical solar layout to the energy decisions behind it.",
      intro: "A useful PV configuration needs more than panel count. Roof fit, orientation, consumption timing and storage all influence the result.",
      groups: [
        { title: "Location & sun", body: "Define the environmental context for the current system.", items: ["Project address / coordinates", "Roof-front bearing", "Time and date", "Seasonal sun position", "PVGIS-calibrated / exact-site data where available"] },
        { title: "Roof & panel fit", body: "Build the physical surface on which the PV system has to fit.", items: ["Two-slope roof", "Four-slope roof", "Single-slope roof", "Roof dimensions and pitch", "Real-size module placement"] },
        { title: "Consumption & storage", body: "Test how household behavior changes the value of the same PV array.", items: ["Residential consumption profiles", "Annual consumption input", "LiFePO₄ battery", "Automatic or manual battery sizing"] },
        { title: "Energy & commercial view", body: "Review the resulting system as a daily energy scenario.", items: ["Installed kWp", "PV production", "Self-sufficiency", "Grid import and export", "System estimate"] },
      ],
    },
    outcomes: {
      label: "Why configure in 3D",
      heading: "A solar proposal that connects roof fit with energy behavior.",
      body: "Panel layout and energy performance are often discussed in separate tools. Combining them makes it easier to explain why a system has a certain size, where the modules fit and how consumption or battery assumptions change the result.",
      items: [
        { title: "For the homeowner", body: "See where the array sits on the roof and compare production, consumption and storage assumptions in one understandable view." },
        { title: "For sales teams", body: "Keep roof geometry, panel count, installed power and the energy scenario synchronized during the same proposal conversation." },
        { title: "For technical planning", body: "Use site context, roof fit and PVGIS-backed data where available as a stronger starting point for a more detailed engineering workflow." },
      ],
    },
    faq: {
      label: "Solar configurator FAQ",
      heading: "Common questions about the 3D solar configurator.",
      items: [
        { question: "Which roof types can I use for the solar layout?", answer: "The current configurator supports two-slope, four-slope and single-slope residential roof families." },
        { question: "Can I change the roof dimensions and pitch?", answer: "Yes. Roof length, depth and pitch are configurable and the available panel surfaces rebuild with the roof." },
        { question: "Does the configurator use the project location?", answer: "Yes. Location is used as context for sun position and site-specific production assumptions; the project also supports PVGIS data through its configured proxy workflow." },
        { question: "Are the panels placed at a physical size?", answer: "Yes. The current preview uses residential module dimensions and keeps installed power tied to modules that fit on the selected roof plane." },
        { question: "Can I model household consumption?", answer: "Yes. The configurator includes several daytime consumption profiles plus an annual consumption input for the energy model." },
        { question: "Can I add battery storage?", answer: "Yes. LiFePO₄ storage can be enabled, automatically sized or manually adjusted within the available controls." },
        { question: "Which energy results are shown?", answer: "The current analysis includes PV production, household demand, self-sufficiency, grid import, grid export, storage and installed system power." },
      ],
    },
    finalCta: {
      eyebrow: "Try the actual product",
      heading: "Build a roof-mounted PV scenario in the browser.",
      body: "Open the solar configurator to test roof geometry, module fit, sun position, household demand and battery storage, or contact us about a configurator for your own energy product.",
      launch: "Launch solar configurator",
      contact: "Discuss a configurator project",
    },
  },
  ro: {
    intro: {
      label: "Configurare sistem fotovoltaic 3D",
      heading: "Configurează împreună acoperișul, panourile și modelul energetic al locuinței.",
      body: "Configuratorul fotovoltaic 360Configurator leagă geometria acoperișului, amplasarea panourilor, contextul geografic, poziția soarelui, consumul locuinței și bateria într-un singur model interactiv. Astfel poți vedea nu doar cum se așază sistemul fotovoltaic pe acoperiș, ci și cum dimensiunea sistemului și profilul de consum influențează rezultatul energetic.",
      launch: "Deschide configuratorul fotovoltaic 3D",
      learn: "Vezi cum funcționează",
    },
    workflow: {
      label: "Cum funcționează",
      heading: "De la adresă și forma acoperișului la estimarea producției în cinci pași.",
      intro: "Fluxul combină potrivirea fizică a panourilor cu ipotezele energetice, astfel încât sistemul fotovoltaic să poată fi analizat ca produs montat pe acoperiș și ca sistem energetic.",
      steps: [
        { title: "Confirmă locația și orientarea", body: "Folosește adresa proiectului și orientarea acoperișului pentru poziția soarelui și estimarea producției." },
        { title: "Configurează acoperișul", body: "Alege tipologia suportată și modifică dimensiunile și panta pentru ca suprafețele disponibile panourilor să urmărească clădirea." },
        { title: "Amplasează panourile fotovoltaice", body: "Alege numărul dorit de module și versantul; configuratorul așază module rezidențiale pe suprafața utilizabilă." },
        { title: "Modelează consumul și bateria", body: "Selectează profilul de consum al locuinței și activează sau dimensionează bateria LiFePO₄ pentru a compara utilizarea energiei pe parcursul zilei." },
        { title: "Verifică rezultatele", body: "Vezi puterea instalată, producția, consumul, autoconsumul, autonomia, energia preluată din rețea și surplusul livrat." },
      ],
    },
    decisions: {
      label: "Ce poți configura",
      heading: "Leagă amplasarea fizică a panourilor de deciziile energetice.",
      intro: "Un sistem fotovoltaic nu este definit doar de numărul de panouri. Spațiul disponibil pe acoperiș, orientarea, momentul consumului și stocarea influențează rezultatul.",
      groups: [
        { title: "Locație și soare", body: "Folosește condițiile reale ale amplasamentului.", items: ["Adresa sau coordonatele proiectului", "Orientarea acoperișului", "Ora și data", "Poziția soarelui în fiecare anotimp", "Date PVGIS pentru locația exactă, unde sunt disponibile"] },
        { title: "Acoperiș și panouri", body: "Construiește suprafața fizică pe care trebuie să încapă sistemul.", items: ["Acoperiș în două ape", "Acoperiș în patru ape", "Acoperiș într-o apă", "Dimensiuni și pantă", "Amplasare module la dimensiune fizică"] },
        { title: "Consum și stocare", body: "Testează cum influențează profilul de consum energia fotovoltaică folosită direct în locuință.", items: ["Profile rezidențiale de consum", "Consum anual", "Baterie LiFePO₄", "Dimensionare automată sau manuală a bateriei"] },
        { title: "Rezultate energetice și estimare", body: "Compară producția sistemului cu necesarul locuinței.", items: ["Putere instalată în kWp", "Producție fotovoltaică", "Autoconsum și autonomie energetică", "Energie preluată și livrată în rețea", "Estimarea sistemului"] },
      ],
    },
    outcomes: {
      label: "De ce configurare 3D",
      heading: "O propunere fotovoltaică adaptată acoperișului și consumului.",
      body: "Amplasarea panourilor și performanța energetică sunt adesea discutate în instrumente separate. Un model comun explică mai ușor de ce sistemul are o anumită dimensiune, unde încap modulele și cum schimbă profilul de consum sau bateria rezultatul.",
      items: [
        { title: "Pentru proprietar", body: "Vezi unde se așază panourile pe acoperiș și compară producția, consumul și stocarea într-o singură vedere." },
        { title: "Pentru vânzare", body: "Păstrează geometria acoperișului, numărul de panouri, puterea instalată și scenariul energetic sincronizate în aceeași ofertă." },
        { title: "Pentru planificare tehnică", body: "Folosește contextul locației, potrivirea pe acoperiș și datele PVGIS acolo unde sunt disponibile ca punct de plecare pentru proiectarea detaliată." },
      ],
    },
    faq: {
      label: "Întrebări despre configuratorul fotovoltaic",
      heading: "Întrebări frecvente despre configurarea unui sistem fotovoltaic 3D.",
      items: [
        { question: "Pe ce tipuri de acoperiș pot amplasa panourile?", answer: "Configuratorul actual include acoperișuri rezidențiale în două ape, patru ape și o apă." },
        { question: "Pot modifica dimensiunile și panta acoperișului?", answer: "Da. Lungimea, adâncimea și panta sunt configurabile, iar suprafețele disponibile pentru panouri se reconstruiesc împreună cu acoperișul." },
        { question: "Configuratorul folosește locația proiectului?", answer: "Da. Locația este folosită pentru contextul solar și ipotezele de producție; proiectul suportă și date PVGIS prin fluxul proxy configurat." },
        { question: "Panourile sunt așezate la dimensiune fizică?", answer: "Da. Previzualizarea folosește dimensiuni de module rezidențiale și leagă puterea instalată de panourile care încap pe versantul selectat." },
        { question: "Pot modela consumul locuinței?", answer: "Da. Sunt disponibile mai multe profile de consum pe parcursul zilei și o valoare de consum anual pentru modelul energetic." },
        { question: "Pot adăuga baterie?", answer: "Da. Stocarea LiFePO₄ poate fi activată, dimensionată automat sau reglată manual în limitele controalelor disponibile." },
        { question: "Ce rezultate energetice sunt afișate?", answer: "Analiza actuală include producția PV, consumul locuinței, autonomia, importul și exportul din rețea, stocarea și puterea instalată." },
      ],
    },
    finalCta: {
      eyebrow: "Testează produsul",
      heading: "Construiește un scenariu fotovoltaic pe acoperiș direct în browser.",
      body: "Deschide configuratorul pentru a testa geometria acoperișului, amplasarea panourilor, poziția soarelui, consumul și bateria sau discută cu noi despre un configurator pentru propriul produs energetic.",
      launch: "Deschide configuratorul fotovoltaic",
      contact: "Discută un proiect de configurator",
    },
  },
  de: {
    intro: {
      label: "3D Photovoltaikplanung",
      heading: "Konfigurieren Sie Dach, PV-Anlage und Haushaltsenergiemodell gemeinsam.",
      body: "Der 360Configurator Solar-Konfigurator verbindet Dachgeometrie, Modulbelegung, geografischen Kontext, Sonnenstand, Haushaltsbedarf und Batteriespeicher in einem interaktiven Modell. So wird nicht nur sichtbar, wie die PV-Anlage auf dem Dach sitzt, sondern auch wie Anlagengröße und Verbrauchsannahmen das Energieergebnis beeinflussen.",
      launch: "3D Solar-Konfigurator öffnen",
      learn: "So funktioniert es",
    },
    workflow: {
      label: "So funktioniert es",
      heading: "Von Standort und Dachgeometrie zu einem täglichen Energieszenario in fünf Schritten.",
      intro: "Der Solar-Workflow kombiniert räumliche Belegung mit Energieannahmen, sodass das PV-System zugleich als Dachprodukt und Energiesystem betrachtet werden kann.",
      steps: [
        { title: "Standort und Ausrichtung festlegen", body: "Nutzen Sie Projektstandort und Dachausrichtung als Kontext für Sonnenstand und Produktionsannahmen." },
        { title: "Dach konfigurieren", body: "Wählen Sie eine unterstützte Dachfamilie und ändern Sie Maße und Neigung, damit die verfügbaren Modulflächen zum Gebäude passen." },
        { title: "PV-Module platzieren", body: "Wählen Sie gewünschte Modulanzahl und Dachfläche; der Konfigurator ordnet Module in realistischen Wohngebäudeabmessungen auf der nutzbaren Fläche an." },
        { title: "Verbrauch und Speicher modellieren", body: "Wählen Sie ein Haushaltslastprofil und aktivieren oder dimensionieren Sie LiFePO₄-Speicher, um die Energienutzung über den Tag zu vergleichen." },
        { title: "Energieergebnis prüfen", body: "Prüfen Sie installierte kWp, Erzeugung, Haushaltsbedarf, Autarkie, Netzbezug/-einspeisung und das tägliche Produktions-/Verbrauchsprofil." },
      ],
    },
    decisions: {
      label: "Was Sie konfigurieren können",
      heading: "Verbinden Sie die physische Modulbelegung mit den Energieentscheidungen dahinter.",
      intro: "Eine sinnvolle PV-Konfiguration wird nicht nur durch die Modulzahl bestimmt. Dachfläche, Ausrichtung, Verbrauchszeitpunkt und Speicher verändern das Ergebnis.",
      groups: [
        { title: "Standort & Sonne", body: "Definieren Sie den Umweltkontext des Systems.", items: ["Projektadresse / Koordinaten", "Dachausrichtung", "Uhrzeit und Datum", "Saisonaler Sonnenstand", "PVGIS-kalibrierte / standortgenaue Daten, sofern verfügbar"] },
        { title: "Dach & Modulbelegung", body: "Bauen Sie die physische Fläche auf, auf der die Anlage Platz finden muss.", items: ["Satteldach", "Walmdach", "Pultdach", "Dachmaße und Neigung", "Modulbelegung in physischer Größe"] },
        { title: "Verbrauch & Speicher", body: "Testen Sie, wie Haushaltsverhalten die Nutzung derselben PV-Erzeugung verändert.", items: ["Wohngebäude-Lastprofile", "Jahresverbrauch", "LiFePO₄-Batterie", "Automatische oder manuelle Speichergröße"] },
        { title: "Energie & kommerzielle Ansicht", body: "Prüfen Sie das System als tägliches Energieszenario.", items: ["Installierte kWp", "PV-Erzeugung", "Autarkie", "Netzbezug und Einspeisung", "Systemschätzung"] },
      ],
    },
    outcomes: {
      label: "Warum 3D konfigurieren",
      heading: "Ein Solarvorschlag, der Dachbelegung und Energieverhalten verbindet.",
      body: "Modulbelegung und Energieperformance werden häufig in getrennten Werkzeugen behandelt. Ein gemeinsamer Zustand erklärt leichter, warum eine Anlage eine bestimmte Größe hat, wo Module Platz finden und wie Verbrauch oder Speicher das Ergebnis verändern.",
      items: [
        { title: "Für Eigentümer", body: "Sehen Sie, wo das PV-Feld auf dem Dach liegt, und vergleichen Sie Erzeugung, Verbrauch und Speicher in einer verständlichen Ansicht." },
        { title: "Für Vertriebsteams", body: "Halten Sie Dachgeometrie, Modulzahl, installierte Leistung und Energieszenario während derselben Angebotsbesprechung synchron." },
        { title: "Für technische Planung", body: "Nutzen Sie Standortkontext, Dachbelegung und PVGIS-Daten, sofern verfügbar, als stärkeren Ausgangspunkt für die detaillierte Planung." },
      ],
    },
    faq: {
      label: "Solar-Konfigurator FAQ",
      heading: "Häufige Fragen zum 3D Solar-Konfigurator.",
      items: [
        { question: "Welche Dachtypen kann ich für die Solarbelegung verwenden?", answer: "Der aktuelle Konfigurator unterstützt Sattel-, Walm- und Pultdächer für Wohngebäude." },
        { question: "Kann ich Dachmaße und Neigung verändern?", answer: "Ja. Dachlänge, Tiefe und Neigung sind konfigurierbar und die verfügbaren Modulflächen bauen sich mit dem Dach neu auf." },
        { question: "Verwendet der Konfigurator den Projektstandort?", answer: "Ja. Der Standort dient als Kontext für Sonnenstand und standortbezogene Produktionsannahmen; das Projekt unterstützt außerdem PVGIS-Daten über den konfigurierten Proxy-Workflow." },
        { question: "Werden Module in physischer Größe platziert?", answer: "Ja. Die aktuelle Vorschau verwendet Wohngebäude-Modulabmessungen und koppelt die installierte Leistung an Module, die auf der gewählten Dachfläche Platz finden." },
        { question: "Kann ich den Haushaltsverbrauch modellieren?", answer: "Ja. Es stehen mehrere Tagesverbrauchsprofile und ein Jahresverbrauchswert für das Energiemodell zur Verfügung." },
        { question: "Kann ich Batteriespeicher hinzufügen?", answer: "Ja. LiFePO₄-Speicher können aktiviert, automatisch dimensioniert oder innerhalb der verfügbaren Regler manuell angepasst werden." },
        { question: "Welche Energieergebnisse werden angezeigt?", answer: "Die aktuelle Analyse umfasst PV-Erzeugung, Haushaltsbedarf, Autarkie, Netzbezug, Netzeinspeisung, Speicher und installierte Systemleistung." },
      ],
    },
    finalCta: {
      eyebrow: "Produkt direkt testen",
      heading: "Bauen Sie ein dachmontiertes PV-Szenario direkt im Browser.",
      body: "Öffnen Sie den Solar-Konfigurator, um Dachgeometrie, Modulbelegung, Sonnenstand, Haushaltsbedarf und Batteriespeicher zu testen, oder sprechen Sie mit uns über einen Konfigurator für Ihr eigenes Energieprodukt.",
      launch: "Solar-Konfigurator starten",
      contact: "Konfigurator-Projekt besprechen",
    },
  },
};

const fenceSeoContent: Record<Locale, ConfiguratorSeoContent> = {
  en: {
    intro: { label: "3D fence planning", heading: "Configure the complete perimeter before estimating it by hand.", body: "The 360Configurator fence tool connects layout geometry, run lengths, bay spacing, panel construction, finishes, gates and foundations in one measurable 3D state. It explains how a selected system follows the actual boundary while keeping every panel and access opening commercially traceable.", launch: "Open the 3D fence configurator", learn: "See how it works" },
    workflow: { label: "How it works", heading: "From boundary geometry to a resolved fence system in five steps.", intro: "Each decision rebuilds the same configured perimeter, keeping the customer view and the technical quantities synchronized.", steps: [
      { title: "Define the perimeter", body: "Choose a straight, L-shaped, U-shaped or closed layout and set the measurable run lengths and corner angle." },
      { title: "Resolve the bay rhythm", body: "Set the target bay width so each run becomes a practical sequence of equal panels and coordinated posts." },
      { title: "Choose panel and finish", body: "Compare vertical, horizontal, privacy and mesh infills, then apply the required powder-coated or wood-effect finish." },
      { title: "Add access and foundations", body: "Position pedestrian or driveway gates and select concrete footings or base-plate installation." },
      { title: "Review BOM and pricing", body: "Use the configured geometry to derive lengths, areas, posts, panels, gates and installation components." },
    ] },
    decisions: { label: "What you can configure", heading: "Coordinate layout, construction and access in one perimeter state.", intro: "Fence systems become difficult to quote when site geometry, panel modules and gates are handled separately. The configurator keeps the decisions connected.", groups: [
      { title: "Layout & dimensions", body: "Build the measurable boundary.", items: ["Straight, L and U layouts", "Four- and five-side closed perimeters", "Run lengths and corner angle", "Fence height"] },
      { title: "Bays & panels", body: "Resolve a manufacturable panel rhythm.", items: ["Target bay width", "Equal panel distribution", "Vertical and horizontal slats", "Privacy and mesh panels"] },
      { title: "Finish & installation", body: "Specify appearance and support conditions.", items: ["Powder-coated colors", "Wood-effect finish", "Concrete footings", "Base plates"] },
      { title: "Access & output", body: "Keep openings and quantities attached to geometry.", items: ["Pedestrian gates", "Driveway gates", "Gate handing", "Live BOM and pricing"] },
    ] },
    outcomes: { label: "Why configure in 3D", heading: "A boundary customers can understand and teams can measure.", body: "The spatial model makes corners, panel rhythm and gates visible while the same state produces the quantities needed downstream.", items: [
      { title: "For customers", body: "See the full perimeter, panel style, finish and gate placement before approving the system." },
      { title: "For sales teams", body: "Keep run lengths, modules and commercial options aligned throughout the proposal." },
      { title: "For production and installation", body: "Use bay, post, gate and foundation data as a structured starting point for delivery." },
    ] },
    faq: { label: "Fence configurator FAQ", heading: "Common questions about the 3D fence configurator.", items: [
      { question: "Which fence layouts can I configure?", answer: "The current system supports straight, L-shaped, U-shaped and closed perimeter layouts, including four- and five-side closed geometry." },
      { question: "Can I control individual run lengths?", answer: "Yes. Active runs expose measurable length controls together with fence height, target bay width and the principal corner angle." },
      { question: "Which panel styles are available?", answer: "The current deployment includes vertical slats, horizontal slats, solid privacy panels and welded mesh." },
      { question: "Can I add gates?", answer: "Yes. Pedestrian and driveway gates can be placed in valid fence bays with their handing retained in the configuration." },
      { question: "Are foundations included?", answer: "Yes. Concrete-footing and base-plate installation conditions are represented in the geometry and material logic." },
      { question: "Does it produce a bill of materials?", answer: "Yes. Lengths, panel area, posts, bays, gates and installation components feed the live BOM and price state." },
      { question: "Do I need to install software?", answer: "No. The configurator runs in a modern browser using WebGL for the interactive 3D view." },
    ] },
    finalCta: { eyebrow: "Try the actual product", heading: "Resolve a complete fence perimeter in the browser.", body: "Open the live configurator to test layouts, panel systems, finishes, gates and foundations, or contact us about adapting the system to your own fence range.", launch: "Launch fence configurator", contact: "Discuss a configurator project" },
  },
  ro: {
    intro: { label: "Proiectare gard 3D", heading: "Configurează perimetrul complet înainte de calculul manual.", body: "Configuratorul de garduri 360Configurator leagă traseul, lungimile, traveile, panourile, finisajele, porțile și fundațiile într-o singură configurație 3D măsurabilă. Sistemul arată cum produsul urmărește limita reală și păstrează fiecare componentă conectată la rezultat.", launch: "Deschide configuratorul de garduri 3D", learn: "Vezi cum funcționează" },
    workflow: { label: "Cum funcționează", heading: "De la geometria limitei la un sistem de gard rezolvat în cinci pași.", intro: "Fiecare decizie reconstruiește același perimetru și păstrează vizualizarea sincronizată cu datele tehnice.", steps: [
      { title: "Definește perimetrul", body: "Alege traseu drept, în L, în U sau închis și setează lungimile și unghiul de colț." }, { title: "Rezolvă ritmul traveilor", body: "Alege lățimea țintă pentru ca fiecare latură să devină o succesiune practică de panouri egale." }, { title: "Alege panoul și finisajul", body: "Compară lamele verticale, orizontale, panouri pline și plasă, apoi aplică finisajul." }, { title: "Adaugă accesul și fundațiile", body: "Poziționează porți pietonale sau auto și alege fundații din beton ori plăci de bază." }, { title: "Verifică BOM-ul și prețul", body: "Folosește geometria pentru lungimi, suprafețe, stâlpi, panouri, porți și montaj." },
    ] },
    decisions: { label: "Ce poți configura", heading: "Coordonează traseul, construcția și accesul în același perimetru.", intro: "Un gard este greu de ofertat când geometria, modulele și porțile sunt tratate separat. Configuratorul le păstrează conectate.", groups: [
      { title: "Traseu și dimensiuni", body: "Construiește limita măsurabilă.", items: ["Trasee drept, L și U", "Perimetre închise", "Lungimi și unghi", "Înălțime"] }, { title: "Travei și panouri", body: "Rezolvă module fabricabile.", items: ["Lățime țintă", "Distribuție egală", "Lamele verticale și orizontale", "Panouri pline și plasă"] }, { title: "Finisaj și montaj", body: "Specifică aspectul și suportul.", items: ["Culori vopsite", "Efect lemn", "Fundații beton", "Plăci de bază"] }, { title: "Acces și rezultate", body: "Conectează golurile la cantități.", items: ["Porți pietonale", "Porți auto", "Sens de deschidere", "Listă de materiale și preț actualizat"] },
    ] },
    outcomes: { label: "De ce configurare 3D", heading: "Un perimetru ușor de înțeles și de măsurat.", body: "Modelul face vizibile colțurile, ritmul panourilor și porțile, iar configurația generează cantitățile necesare.", items: [{ title: "Pentru client", body: "Vede traseul, panourile, finisajul și porțile înainte de aprobare." }, { title: "Pentru vânzări", body: "Păstrează dimensiunile și opțiunile comerciale în aceeași ofertă." }, { title: "Pentru producție și montaj", body: "Folosește traveile, stâlpii, porțile și fundațiile ca date structurate." }] },
    faq: { label: "Întrebări despre garduri", heading: "Întrebări frecvente despre configuratorul de garduri 3D.", items: [{ question: "Ce trasee pot configura?", answer: "Sistemul acceptă trasee drepte, în L, în U și perimetre închise cu patru sau cinci laturi." }, { question: "Pot controla lungimile?", answer: "Da. Laturile active, înălțimea, traveea țintă și unghiul principal sunt configurabile." }, { question: "Ce panouri sunt disponibile?", answer: "Lamele verticale, orizontale, panouri pline și plasă sudată." }, { question: "Pot adăuga porți?", answer: "Da. Porțile pietonale și auto pot ocupa travei valide." }, { question: "Sunt incluse fundațiile?", answer: "Da. Sunt disponibile fundații din beton și plăci de bază." }, { question: "Există listă de materiale?", answer: "Da. Geometria actualizează BOM-ul și prețul." }, { question: "Trebuie instalat un program?", answer: "Nu. Configuratorul rulează în browser cu WebGL." }] },
    finalCta: { eyebrow: "Testează produsul", heading: "Rezolvă un perimetru complet direct în browser.", body: "Testează traseele, panourile, finisajele, porțile și fundațiile sau discută cu noi despre adaptarea sistemului la gama ta.", launch: "Deschide configuratorul", contact: "Discută un proiect" },
  },
  de: {
    intro: { label: "3D Zaunplanung", heading: "Konfigurieren Sie den vollständigen Perimeter vor der manuellen Kalkulation.", body: "Der 360Configurator Zaun-Konfigurator verbindet Verlauf, Längen, Feldteilung, Paneele, Oberflächen, Tore und Fundamente in einem messbaren 3D-Zustand. Das System zeigt, wie der Zaun der realen Grenze folgt und hält jede Komponente kaufmännisch nachvollziehbar.", launch: "3D Zaun-Konfigurator öffnen", learn: "So funktioniert es" },
    workflow: { label: "So funktioniert es", heading: "Von der Grenzgeometrie zum aufgelösten Zaunsystem in fünf Schritten.", intro: "Jede Entscheidung baut denselben Perimeter neu auf und hält Kundenansicht und technische Mengen synchron.", steps: [{ title: "Perimeter definieren", body: "Wählen Sie gerade, L-, U- oder geschlossene Verläufe und setzen Sie Längen und Winkel." }, { title: "Feldraster auflösen", body: "Eine Zielfeldbreite erzeugt praktische, gleichmäßige Paneele und koordinierte Pfosten." }, { title: "Paneel und Oberfläche wählen", body: "Vergleichen Sie Lamellen, Sichtschutz und Gitter und wenden Sie die Oberfläche an." }, { title: "Zugang und Fundamente ergänzen", body: "Positionieren Sie Personen- oder Einfahrtstore und wählen Sie Beton oder Fußplatten." }, { title: "Stückliste und Preis prüfen", body: "Leiten Sie Längen, Flächen, Pfosten, Paneele, Tore und Montage aus der Geometrie ab." }] },
    decisions: { label: "Was Sie konfigurieren können", heading: "Koordinieren Sie Verlauf, Konstruktion und Zugang in einem Perimeterzustand.", intro: "Zaunsysteme sind schwer zu kalkulieren, wenn Geometrie, Module und Tore getrennt behandelt werden.", groups: [{ title: "Verlauf & Maße", body: "Bauen Sie die messbare Grenze.", items: ["Gerade, L- und U-Verläufe", "Geschlossene Perimeter", "Längen und Winkel", "Zaunhöhe"] }, { title: "Felder & Paneele", body: "Lösen Sie fertigungsgerechte Module auf.", items: ["Zielfeldbreite", "Gleichmäßige Teilung", "Vertikale und horizontale Lamellen", "Sichtschutz und Gitter"] }, { title: "Oberfläche & Montage", body: "Definieren Sie Aussehen und Auflager.", items: ["Pulverbeschichtung", "Holzoptik", "Betonfundamente", "Fußplatten"] }, { title: "Zugang & Output", body: "Verbinden Sie Öffnungen mit Mengen.", items: ["Personentore", "Einfahrtstore", "Anschlag", "Stückliste und Live-Preis"] }] },
    outcomes: { label: "Warum 3D konfigurieren", heading: "Eine Grenze, die Kunden verstehen und Teams messen können.", body: "Das räumliche Modell macht Ecken, Feldraster und Tore sichtbar und liefert gleichzeitig die nachgelagerten Mengen.", items: [{ title: "Für Kunden", body: "Sehen Sie Verlauf, Paneele, Oberfläche und Tore vor der Freigabe." }, { title: "Für Vertrieb", body: "Halten Sie Maße, Module und Optionen im selben Angebot synchron." }, { title: "Für Fertigung und Montage", body: "Nutzen Sie Felder, Pfosten, Tore und Fundamente als strukturierte Übergabe." }] },
    faq: { label: "Zaun-Konfigurator FAQ", heading: "Häufige Fragen zum 3D Zaun-Konfigurator.", items: [{ question: "Welche Verläufe kann ich konfigurieren?", answer: "Gerade, L-, U- und geschlossene Perimeter mit vier oder fünf Seiten." }, { question: "Kann ich Lauflängen steuern?", answer: "Ja. Aktive Längen, Höhe, Zielfeldbreite und Hauptwinkel sind konfigurierbar." }, { question: "Welche Paneele sind verfügbar?", answer: "Vertikale und horizontale Lamellen, Sichtschutzpaneele und Schweißgitter." }, { question: "Kann ich Tore ergänzen?", answer: "Ja. Personen- und Einfahrtstore können in gültigen Feldern platziert werden." }, { question: "Sind Fundamente enthalten?", answer: "Ja. Betonfundamente und Fußplatten stehen zur Verfügung." }, { question: "Gibt es eine Stückliste?", answer: "Ja. Geometrie, Stückliste und Preis bleiben verbunden." }, { question: "Muss Software installiert werden?", answer: "Nein. Der Konfigurator läuft im Browser mit WebGL." }] },
    finalCta: { eyebrow: "Produkt direkt testen", heading: "Lösen Sie einen vollständigen Zaunperimeter im Browser auf.", body: "Testen Sie Verläufe, Paneele, Oberflächen, Tore und Fundamente oder sprechen Sie mit uns über die Anpassung an Ihr Sortiment.", launch: "Zaun-Konfigurator starten", contact: "Projekt besprechen" },
  },
};

export const configuratorSeoContent: Record<ConfiguratorSlug, Record<Locale, ConfiguratorSeoContent>> = {
  pergola: pergolaSeoContent,
  roof: roofSeoContent,
  window: windowSeoContent,
  hall: hallSeoContent,
  solar: solarSeoContent,
  fence: fenceSeoContent,
};
