// Generated from shared-ui/src/tenantDomains.js. Do not edit directly.
// Canonical tenant-domain policy. Backend copies are generated by
// scripts/build/sync-tenant-domains.mjs and checked in CI.
export const TENANT_DOMAIN_ROOTS = Object.freeze({
  'en-US': '360configurator.com',
  'ro-RO': '360configurator.ro',
  'de-DE': '360konfigurator.de',
});

export const TENANT_ORIGIN_PATTERN = /^https:\/\/([a-z0-9](?:[a-z0-9-]{0,38}[a-z0-9])?)\.(?:360configurator\.com|360configurator\.ro|360konfigurator\.de)$/;

export const TENANT_SLUG_PATTERN = /^[a-z0-9](?:[a-z0-9-]{0,38}[a-z0-9])?$/;
export const RESERVED_TENANT_SLUGS = Object.freeze([
  'www', 'aks', 'admin', 'api', 'app', 'assets', 'auth', 'billing',
  'cdn', 'demo', 'dev', 'ftp', 'mail', 'staging', 'static',
  'status', 'support', 'test',
]);

export function validTenantSlug(value) {
  return typeof value === 'string'
    && TENANT_SLUG_PATTERN.test(value)
    && !RESERVED_TENANT_SLUGS.includes(value);
}

export function tenantDomainsForSlug(slug) {
  if (!validTenantSlug(slug)) return [];
  return Object.values(TENANT_DOMAIN_ROOTS).map((root) => `${slug}.${root}`);
}

export function tenantDomainContext(hostname = '') {
  const host = String(hostname).trim().toLowerCase().replace(/\.$/, '');
  for (const [locale, root] of Object.entries(TENANT_DOMAIN_ROOTS)) {
    const suffix = `.${root}`;
    if (!host.endsWith(suffix)) continue;
    const slug = host.slice(0, -suffix.length);
    if (!validTenantSlug(slug)) return null;
    return { slug, hostname: host, locale, canonicalDomain: `${slug}.${TENANT_DOMAIN_ROOTS['en-US']}` };
  }
  return null;
}

export function tenantOriginContext(origin = '') {
  try {
    const url = new URL(String(origin));
    if (url.protocol !== 'https:' || url.port || url.username || url.password
      || url.pathname !== '/' || url.search || url.hash) return null;
    return tenantDomainContext(url.hostname);
  } catch {
    return null;
  }
}

// The immutable .com domain remains the ownership anchor. Aliases are derived
// only from this policy, never trusted from client-supplied domains[] values.
// Legacy documents without a domain still belong to their validated document ID.
export function tenantRecordMatchesHost(tenant, hostname) {
  const context = tenantDomainContext(hostname);
  if (!context || !tenant || typeof tenant !== 'object') return false;
  if (tenant.slug && tenant.slug !== context.slug) return false;
  const canonical = String(tenant.domain || context.canonicalDomain).trim().toLowerCase();
  return canonical === context.canonicalDomain;
}
