const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: process.env.ROOF_TEST_BROWSER || undefined, args: ['--no-sandbox', '--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  if (process.env.ROOF_TEST_THREE) {
    await page.route('https://cdn.jsdelivr.net/npm/three@0.169.0/**', route => {
      const path = route.request().url().split('three@0.169.0/')[1];
      return route.fulfill({ path: require('node:path').join(process.env.ROOF_TEST_THREE, path), contentType: 'text/javascript' });
    });
  }
  const errors = [];
  page.on('pageerror', error => { errors.push(error.message); console.error('Browser:', error.message); });
  await page.goto('http://127.0.0.1:8080/roof-configurator/?profile', { waitUntil: 'domcontentloaded' });
  await page.waitForFunction(() => window.ROOF_CONFIGURATOR_API, { timeout: 30000 });
  await page.locator('[data-roof-type="layout"]').click();
  await page.locator('#editRoofLayout').click();
  const editor = page.locator('.roof-layout-dialog');
  const deleteButton = editor.locator('[data-action="delete"]');
  assert.ok(await deleteButton.isDisabled());
  // Select the middle of the default roof ridge in actual screen coordinates.
  const ridge = await editor.locator('.layout-drawing > svg').evaluate(svg => {
    const nodes = svg.querySelectorAll('.layout-node');
    const a = nodes[2], b = nodes[5];
    const p = new DOMPoint((Number(a.getAttribute('cx')) + Number(b.getAttribute('cx'))) / 2,
      (Number(a.getAttribute('cy')) + Number(b.getAttribute('cy'))) / 2).matrixTransform(svg.getScreenCTM());
    return { x: p.x, y: p.y };
  });
  await page.mouse.click(ridge.x, ridge.y);
  assert.ok(await deleteButton.isEnabled());
  await page.keyboard.press('Delete');
  assert.match(await page.locator('.layout-summary').textContent(), /1 surfaces/);
  await editor.locator('[data-action="undo"]').click();
  assert.match(await page.locator('.layout-summary').textContent(), /2 surfaces/);
  await editor.locator('[data-action="redo"]').click();
  assert.match(await page.locator('.layout-summary').textContent(), /1 surfaces/);
  await editor.locator('[data-action="undo"]').click();
  await page.locator('#layoutPointSelect').selectOption('0');
  await deleteButton.click();
  assert.equal(await page.locator('#layoutPointSelect option').count(), 6);
  await editor.locator('[data-action="undo"]').click();
  assert.equal(await page.locator('#layoutPointSelect option').count(), 7);
  await page.locator('.layout-setup summary').click();
  await page.locator('#layoutExample').selectOption('lshape');
  await page.locator('.roof-layout-dialog [data-action="example"]').click();
  assert.match(await page.locator('.layout-summary').textContent(), /6 surfaces/);
  await page.locator('.roof-layout-dialog [data-action="apply"]').click();
  const lShape = await page.evaluate(() => window.ROOF_CONFIGURATOR_API.captureState().roofLayout);
  assert.equal(lShape.faces.length, 6);
  assert.ok(lShape.boundary.every(id => lShape.vertices[id].h === 0));
  await page.screenshot({ path: '/tmp/roof-lshape-3d.png' });
  await page.locator('#editRoofLayout').click();
  await page.locator('#layoutExample').selectOption('hip');
  await page.locator('.roof-layout-dialog [data-action="example"]').click();
  await page.screenshot({ path: '/tmp/roof-layout-desktop.png' });
  await page.locator('.roof-layout-dialog [data-action="apply"]').click();
  const saved = await page.evaluate(() => window.ROOF_CONFIGURATOR_API.captureState());
  assert.equal(saved.roofType, 'layout');
  assert.equal(saved.roofLayout.faces.length, 4);
  await page.screenshot({ path: '/tmp/roof-layout-3d.png' });
  await page.locator('#editRoofLayout').click();
  await page.locator('#layoutExample').selectOption('saw');
  await page.locator('.roof-layout-dialog [data-action="example"]').click();
  await page.locator('.roof-layout-dialog [data-action="undo"]').click();
  assert.match(await page.locator('.layout-summary').textContent(), /4 surfaces/);
  await page.locator('.roof-layout-dialog [data-action="redo"]').click();
  await page.locator('.roof-layout-dialog [data-action="apply"]').click();
  const saw = await page.evaluate(() => window.ROOF_CONFIGURATOR_API.captureState());
  assert.equal(saw.roofLayout.faces.length, 4);
  assert.equal(await page.evaluate(s => window.ROOF_CONFIGURATOR_API.restoreState(s), saved), true);
  assert.deepEqual(await page.evaluate(() => window.ROOF_CONFIGURATOR_API.captureState().roofLayout), saved.roofLayout);
  const invalid = structuredClone(saved);
  invalid.roofLayout.vertices[0].x = null;
  assert.equal(await page.evaluate(s => window.ROOF_CONFIGURATOR_API.restoreState(s), invalid), false);
  assert.deepEqual(await page.evaluate(() => window.ROOF_CONFIGURATOR_API.captureState().roofLayout), saved.roofLayout);
  await page.locator('#editRoofLayout').click();
  await page.locator('.roof-layout-dialog [data-action="draw"]').click();
  const svg = page.locator('.layout-drawing svg');
  const clickAt = async (x, y) => {
    const p = await svg.evaluate((el, p) => {
      const v = new DOMPoint(p.x, p.y).matrixTransform(el.getScreenCTM());
      return { x: v.x, y: v.y };
    }, { x, y });
    await page.mouse.click(p.x, p.y);
  };
  for (const p of [[220, 180], [560, 180], [560, 400], [220, 400]]) await clickAt(...p);
  await page.locator('.roof-layout-dialog [data-action="finish"]').click();
  assert.match(await page.locator('.layout-summary').textContent(), /2 surfaces/);
  await page.locator('.roof-layout-dialog [data-action="apply"]').click();
  assert.equal(await page.evaluate(() => window.ROOF_CONFIGURATOR_API.captureState().roofLayout.faces.length), 2);
  assert.ok(await page.evaluate(() => window.ROOF_CONFIGURATOR_API.captureState().roofLayout.vertices.some(p => p.h > 0)), 'New drawings must be pitched');
  await page.locator('#editRoofLayout').click();
  const dragNode = async (id, dx, dy, shift = false) => {
    const box = await page.locator('.layout-node').nth(id).boundingBox();
    const x = box.x + box.width / 2, y = box.y + box.height / 2;
    if (shift) await page.keyboard.down('Shift');
    await page.mouse.move(x, y);
    await page.mouse.down();
    await page.mouse.move(x + dx, y + dy, { steps: 8 });
    await page.mouse.up();
    if (shift) await page.keyboard.up('Shift');
  };
  await page.locator('#layoutPointSelect').selectOption('0');
  const beforeX = Number(await page.locator('#layoutX').inputValue());
  const beforeH = Number(await page.locator('#layoutH').inputValue());
  await dragNode(0, 30, 0);
  const movedX = Number(await page.locator('#layoutX').inputValue());
  assert.ok(movedX > beforeX, 'Mouse dragging must move the point');
  await page.locator('.roof-layout-dialog [data-action="undo"]').click();
  await page.locator('#layoutPointSelect').selectOption('0');
  assert.equal(Number(await page.locator('#layoutX').inputValue()), beforeX);
  await page.locator('.roof-layout-dialog [data-action="redo"]').click();
  await page.locator('#layoutPointSelect').selectOption('0');
  assert.equal(Number(await page.locator('#layoutX').inputValue()), movedX);
  await dragNode(0, 0, -30, true);
  assert.ok(Number(await page.locator('#layoutH').inputValue()) > beforeH, 'Shift-drag must raise the point');
  const from = await page.locator('.layout-node').nth(0).boundingBox();
  const to = await page.locator('.layout-node').nth(2).boundingBox();
  await dragNode(0, to.x - from.x, to.y - from.y);
  assert.equal(Number(await page.locator('#layoutX').inputValue()), movedX, 'Invalid drag must roll back');
  // Click actual projected node coordinates for selection.
  const node = await page.locator('.layout-node').first().boundingBox();
  await page.mouse.click(node.x + node.width / 2, node.y + node.height / 2);
  await page.locator('#layoutH').fill('2');
  await page.locator('.roof-layout-dialog [data-action="point"]').click();
  await page.locator('.roof-layout-dialog [data-action="apply"]').click();
  assert.equal(await page.evaluate(() => window.ROOF_CONFIGURATOR_API.captureState().roofLayout.vertices[0].h), 2);
  await page.locator('#editRoofLayout').click();
  await page.locator('.roof-layout-dialog [data-action="split"]').click();
  for (const id of [0, 5]) {
    const box = await page.locator('.layout-node').nth(id).boundingBox();
    await page.mouse.click(box.x + box.width / 2, box.y + box.height / 2);
  }
  assert.match(await page.locator('.layout-summary').textContent(), /3 surfaces/);
  await page.locator('.roof-layout-dialog [data-action="apply"]').click();
  assert.equal(await page.evaluate(() => window.ROOF_CONFIGURATOR_API.captureState().roofLayout.faces.length), 3);
  await page.locator('#editRoofLayout').click();
  await page.locator('#layoutExample').selectOption('hip');
  await page.locator('.roof-layout-dialog [data-action="example"]').click();
  await page.locator('.roof-layout-dialog [data-action="cancel"]').last().click();
  assert.equal(await page.evaluate(() => window.ROOF_CONFIGURATOR_API.captureState().roofLayout.faces.length), 3);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('#editRoofLayout').click();
  await page.screenshot({ path: '/tmp/roof-layout-mobile.png' });
  assert.equal(await page.locator('.roof-layout-dialog').evaluate(el => el.scrollWidth <= el.clientWidth + 1), true);
  await page.locator('.roof-layout-dialog [data-action="cancel"]').last().click();
  await page.evaluate(() => window.ROOF_CONFIGURATOR_API.resetConfiguration());
  assert.equal(await page.evaluate(() => window.ROOF_CONFIGURATOR_API.captureState().roofType), 'gable');
  assert.deepEqual(errors, []);
  await browser.close();
  console.log('PASS: desktop/mobile editor, drawing, point heights, examples, undo/redo, 3D, restore rejection, reset.');
})().catch(error => { console.error(error); process.exit(1); });
