import { SiteHeader } from "./site-header";
import { SiteFooter } from "./site-footer";
import { SmoothScroll } from "./smooth-scroll";
import { ContactForm } from "./contact-form";
import { contactEmail, contactPhone, localizedPath, type Locale } from "../lib/i18n";
import { absoluteUrl, breadcrumbSchema, graphSchema, organizationSchema, siteUrl, websiteSchema } from "../lib/seo";

const aboutCopy = {
  en: {
    index: "01 / About 360Configurator", eyebrow: "A product initiative by 360design", titleA: "We make industrial logic", titleB: "visible, usable, valuable.", intro: "360Configurator is a focused product initiative for turning complex physical products into clear, connected digital experiences.",
    origin: "Born from practice", originTitle: "Built where design, software and real product constraints meet.", originBody: "Our foundation comes from years of creating digital products and interactive experiences at 360design. 360Configurator concentrates that experience into one discipline: spatial product configuration for manufacturers, sales teams and their customers.",
    method: "How we work", principles: [["Human clarity", "We begin with the people who must understand, sell, specify and manufacture the product. Advanced technology earns its place by making their decisions clearer."], ["Engineering fidelity", "We model dimensions, dependencies, compatibility and assemblies as product logic—not as visual theatre. What users see must remain connected to what can be built."], ["Commercial continuity", "Configuration, pricing, BOM and downstream handoff belong to one state. We design the experience so information does not fracture between customer, sales and operations."], ["Research in motion", "The platform continues to evolve through active research and development. Each deployment expands the system’s capacity for new industries, rules and product families."]],
    closingA: "Not another 3D viewer.", closingB: "A new operating layer for configurable products.", cta: "Discuss your product",
  },
  ro: {
    index: "01 / Despre 360Configurator", eyebrow: "Un produs 360design", titleA: "Facem produsele complexe", titleB: "mai ușor de înțeles și de vândut.", intro: "360Configurator transformă produsele fizice cu multe opțiuni și reguli în experiențe 3D clare pentru clienți, vânzări și echipe tehnice.",
    origin: "Creat din experiență practică", originTitle: "Designul, software-ul și regulile produsului lucrează împreună.", originBody: "360Configurator pornește din experiența 360design în produse digitale și experiențe interactive. Aplicăm această experiență produselor care trebuie configurate corect înainte de ofertare, fabricație sau montaj.",
    method: "Cum lucrăm", principles: [["Claritate pentru utilizatori", "Pornim de la oamenii care trebuie să înțeleagă, să vândă, să specifice și să fabrice produsul. Tehnologia are valoare atunci când îi ajută să ia decizii mai clare."], ["Precizie tehnică", "Modelăm dimensiunile, dependențele, compatibilitatea și ansamblurile după regulile produsului. Ceea ce vede utilizatorul trebuie să poată fi fabricat."], ["Date comerciale conectate", "Configurația, prețul, lista de materiale și datele proiectului rămân împreună. Informația nu mai trebuie refăcută între client, vânzări și operațiuni."], ["Dezvoltare continuă", "Platforma evoluează prin proiecte reale. Fiecare implementare adaugă reguli, produse și instrumente care pot fi folosite în industrii noi."]],
    closingA: "Mai mult decât un model 3D.", closingB: "Un proces complet de configurare și ofertare.", cta: "Discută despre produsul tău",
  },
  de: {
    index: "01 / Über 360Configurator", eyebrow: "Eine Produktinitiative von 360design", titleA: "Wir machen industrielle Logik", titleB: "sichtbar, nutzbar, wertvoll.", intro: "360Configurator ist eine fokussierte Produktinitiative, die komplexe physische Produkte in klare, verknüpfte digitale Erlebnisse übersetzt.",
    origin: "Aus der Praxis entstanden", originTitle: "Entwickelt an der Schnittstelle von Design, Software und realen Produktanforderungen.", originBody: "Unsere Grundlage ist die langjährige Arbeit von 360design an digitalen Produkten und interaktiven Erlebnissen. 360Configurator bündelt diese Erfahrung in einer Disziplin: räumliche Produktkonfiguration für Hersteller, Vertriebsteams und ihre Kunden.",
    method: "Unsere Arbeitsweise", principles: [["Menschliche Klarheit", "Wir beginnen bei den Menschen, die ein Produkt verstehen, verkaufen, spezifizieren und fertigen müssen. Technologie schafft Wert, wenn sie Entscheidungen klarer macht."], ["Technische Präzision", "Wir modellieren Maße, Abhängigkeiten, Kompatibilität und Baugruppen als Produktlogik—nicht als visuelles Theater. Was Nutzer sehen, muss baubar bleiben."], ["Kaufmännische Kontinuität", "Konfiguration, Preis, Stückliste und Systemübergabe gehören zu einem Zustand. Informationen dürfen zwischen Kunde, Vertrieb und Betrieb nicht auseinanderbrechen."], ["Forschung in Bewegung", "Die Plattform entwickelt sich durch aktive Forschung und Entwicklung weiter. Jede Implementierung erweitert ihre Fähigkeiten für neue Branchen, Regeln und Produktfamilien."]],
    closingA: "Nicht noch ein 3D-Viewer.", closingB: "Eine neue operative Ebene für konfigurierbare Produkte.", cta: "Über Ihr Produkt sprechen",
  },
} as const;

const contactCopy = {
  en: { index: "01 / Contact", titleA: "Bring us the product", titleB: "that resists simplification.", intro: "Tell us what people need to configure, what rules govern it and what the finished state must produce. We will start with the product—not a template.", signal: "Direct project channel", email: "Project correspondence", phone: "Phone", brief: "A useful first brief", items: ["Product family and target users", "Dimensions, options and compatibility rules", "Pricing, BOM or integration requirements", "Existing CAD, 3D or product data"], response: "We review every enquiry directly and reply with the questions needed to define a meaningful first scope." },
  ro: { index: "01 / Contact", titleA: "Ai un produs complex?", titleB: "Hai să-i construim configuratorul.", intro: "Spune-ne ce trebuie să aleagă utilizatorii, ce reguli trebuie respectate și ce date trebuie generate la final. Pornim de la produsul tău și de la procesul real de vânzare.", signal: "Discuție directă despre proiect", email: "E-mail", phone: "Telefon", brief: "Ce ne ajută la prima discuție", items: ["Familia de produse și utilizatorii vizați", "Dimensiunile, opțiunile și regulile de compatibilitate", "Cerințele de preț, lista de materiale și integrările", "Modelele CAD, 3D sau alte date de produs disponibile"], response: "Analizăm fiecare solicitare și revenim cu întrebările necesare pentru a defini ce include proiectul și care este următorul pas." },
  de: { index: "01 / Kontakt", titleA: "Bringen Sie uns das Produkt,", titleB: "das sich nicht vereinfachen lässt.", intro: "Beschreiben Sie, was Nutzer konfigurieren, welche Regeln gelten und welches Ergebnis der fertige Zustand liefern muss. Wir beginnen beim Produkt—nicht bei einer Vorlage.", signal: "Direkter Projektkanal", email: "Projektkorrespondenz", phone: "Telefon", brief: "Ein hilfreiches Erstbriefing", items: ["Produktfamilie und Zielgruppen", "Abmessungen, Optionen und Kompatibilitätsregeln", "Preis-, Stücklisten- oder Integrationsanforderungen", "Vorhandene CAD-, 3D- oder Produktdaten"], response: "Wir prüfen jede Anfrage direkt und melden uns mit den Fragen, die für einen sinnvollen ersten Projektrahmen erforderlich sind." },
} as const;

export function AboutPage({ locale }: { locale: Locale }) {
  const copy = aboutCopy[locale]; const path = localizedPath(locale, "/about");
  const schema = graphSchema([organizationSchema(locale, copy.intro), websiteSchema(locale, copy.intro), { "@type": "AboutPage", "@id": `${absoluteUrl(locale,"/about")}#webpage`, url: absoluteUrl(locale,"/about"), name: copy.index, description: copy.intro, inLanguage: locale, isPartOf: { "@id": `${siteUrl(locale)}/#website` }, breadcrumb: { "@id": `${absoluteUrl(locale,"/about")}#breadcrumb` } }, breadcrumbSchema(locale,[{name:"360Configurator",path:"/"},{name:copy.index.replace(/^01 \/ /,""),path:"/about"}])]);
  return <main className="site-shell editorial-page about-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><SmoothScroll/><SiteHeader locale={locale} currentPath={path}/>
    <section className="editorial-hero page-frame"><div className="editorial-orbit" aria-hidden="true"><i/><i/><i/></div><span className="mono-label">{copy.index}</span><p className="editorial-eyebrow">{copy.eyebrow}</p><h1>{copy.titleA}<br/><em>{copy.titleB}</em></h1><p className="editorial-intro">{copy.intro}</p></section>
    <section className="editorial-origin"><div className="page-frame"><span className="mono-label">{copy.origin}</span><h2>{copy.originTitle}</h2><p>{copy.originBody}</p></div></section>
    <section className="editorial-principles"><div className="page-frame"><span className="mono-label">{copy.method}</span><div className="principle-grid">{copy.principles.map(([title,body],index)=><article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>
    <section className="editorial-close"><div className="page-frame"><h2>{copy.closingA}<br/><em>{copy.closingB}</em></h2><a className="project-link" href={localizedPath(locale,"/contact")}><span>{copy.cta}</span><b>↗</b></a></div></section><SiteFooter locale={locale}/>
  </main>;
}

export function ContactPage({ locale }: { locale: Locale }) {
  const copy = contactCopy[locale]; const path = localizedPath(locale, "/contact"); const email = contactEmail(locale);
  const schema = graphSchema([organizationSchema(locale, copy.intro), websiteSchema(locale, copy.intro), { "@type": "ContactPage", "@id": `${absoluteUrl(locale,"/contact")}#webpage`, url: absoluteUrl(locale,"/contact"), name: copy.index, description: copy.intro, inLanguage: locale, isPartOf: { "@id": `${siteUrl(locale)}/#website` }, breadcrumb: { "@id": `${absoluteUrl(locale,"/contact")}#breadcrumb` }, mainEntity: { "@type": "ContactPoint", contactType: "sales", email, telephone: contactPhone.international, availableLanguage: ["English","Romanian","German"] } }, breadcrumbSchema(locale,[{name:"360Configurator",path:"/"},{name:copy.index.replace(/^01 \/ /,""),path:"/contact"}])]);
  return <main className="site-shell editorial-page contact-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><SmoothScroll/><SiteHeader locale={locale} currentPath={path}/>
    <section className="contact-hero page-frame"><div className="contact-hero-copy"><span className="mono-label">{copy.index}</span><h1>{copy.titleA}<br/><em>{copy.titleB}</em></h1><p>{copy.intro}</p></div><div className="contact-signal"><span>{copy.signal}</span><b>360°</b><i/></div></section>
    <section className="contact-workspace"><div className="page-frame contact-layout"><aside><div className="contact-channels"><div className="contact-channel"><span className="mono-label">{copy.email}</span><a href={`mailto:${email}`}>{email}</a></div><div className="contact-channel"><span className="mono-label">{copy.phone}</span><a href={`tel:${contactPhone.international}`}>{contactPhone.display}</a></div></div><h2>{copy.brief}</h2><ol>{copy.items.map((item,index)=><li key={item}><span>0{index+1}</span>{item}</li>)}</ol><p>{copy.response}</p></aside><ContactForm locale={locale}/></div></section>
    <SiteFooter locale={locale}/>
  </main>;
}
