import { SiteHeader } from "./site-header";
import { SiteFooter } from "./site-footer";
import { SmoothScroll } from "./smooth-scroll";
import { PricingPathSelector } from "./pricing-path-selector";
import { PricingSolid } from "./pricing-solid";
import { PricingFaq } from "./pricing-faq";
import { localizedPath, type Locale } from "../lib/i18n";
import { pricingCopy } from "../lib/pricing-copy";
import { absoluteUrl, breadcrumbSchema, graphSchema, organizationSchema, siteUrl, SITE_URL, websiteSchema } from "../lib/seo";

export function PricingPage({ locale }: { locale: Locale }) {
  const copy = pricingCopy[locale];
  const path = localizedPath(locale, "/pricing");
  const schema = graphSchema([organizationSchema(locale, copy.hero.body), websiteSchema(locale, copy.hero.body), { "@type": "WebPage", "@id": `${absoluteUrl(locale, "/pricing")}#webpage`, url: absoluteUrl(locale, "/pricing"), name: copy.nav, description: copy.hero.body, inLanguage: locale, isPartOf: { "@id": `${siteUrl(locale)}/#website` }, about: { "@id": `${SITE_URL}/#organization` }, breadcrumb: { "@id": `${absoluteUrl(locale, "/pricing")}#breadcrumb` } }, { "@type": "FAQPage", "@id": `${absoluteUrl(locale, "/pricing")}#faq`, mainEntity: copy.faq.items.map(([name,text])=>({ "@type":"Question", name, acceptedAnswer:{ "@type":"Answer", text } })) }, breadcrumbSchema(locale, [{ name: "360Configurator", path: "/" }, { name: copy.nav, path: "/pricing" }])]);
  return <main className="site-shell pricing-page">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <SmoothScroll/><SiteHeader locale={locale} currentPath={path}/>
    <section className="pricing-hero page-frame"><div className="pricing-hero-grid" aria-hidden="true"><i/><i/><i/><i/><span>01</span><span>02</span><span>03</span></div><div className="pricing-hero-copy"><span className="mono-label">{copy.hero.index}</span><h1>{copy.hero.titleA}<br/><em>{copy.hero.titleB}</em></h1><p>{copy.hero.body}</p><a className="text-link" href="#deployment-paths">{copy.selectorLabel}<span>↓</span></a></div></section>
    <section className="deployment-paths" id="deployment-paths"><div className="page-frame"><PricingPathSelector locale={locale}/></div></section>
    <section className="system-field"><div className="page-frame"><div className="pricing-wide-heading"><span className="mono-label">{copy.selectSystem.label}</span><div><h2>{copy.selectSystem.title}</h2><p>{copy.selectSystem.body}</p></div></div><div className="system-field-content"><PricingSolid shape="d6" items={copy.selectSystem.systems} description={copy.selectSystem.body} label={copy.selectSystem.title}/><ol>{copy.selectSystem.systems.map((system, index) => <li key={system}><span>{String(index + 1).padStart(2, "0")}</span><strong>{system}</strong><i>{copy.selectSystem.status}</i></li>)}</ol></div></div></section>
    <section className="commercial-boundary"><div className="page-frame"><div className="boundary-heading"><span className="mono-label">{copy.boundary.label}</span><div><h2>{copy.boundary.title}</h2><p>{copy.boundary.body}</p></div></div><div className="boundary-grid"><article className="boundary-included"><header><span>IN / 01</span><h3>{copy.boundary.included}</h3></header><ul>{copy.boundary.includedItems.map(item => <li key={item}>{item}<b>{copy.boundary.includedStatus}</b></li>)}</ul></article><article className="boundary-scoped"><header><span>OUT / 02</span><h3>{copy.boundary.scoped}</h3></header><ul>{copy.boundary.scopedItems.map(item => <li key={item}>{item}<b>{copy.boundary.scopedStatus}</b></li>)}</ul></article></div></div></section>
    <section className="pricing-platform"><div className="page-frame"><div className="pricing-platform-hero"><div className="pricing-platform-console"><span className="mono-label">{copy.platform.label}</span><PricingSolid shape="d4" items={copy.platform.items.map(item=>item[0])} descriptions={copy.platform.items.map(item=>item[1])} description={copy.platform.title} label={copy.platform.title}/></div><h2>{copy.platform.title}</h2></div><div className="pricing-platform-grid">{copy.platform.items.map(([title, body], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>
    <section className="scope-factors"><div className="page-frame"><div className="pricing-wide-heading"><span className="mono-label">{copy.scope.label}</span><div><h2>{copy.scope.title}</h2><p>{copy.scope.intro}</p></div></div><div className="scope-content"><PricingSolid shape="d8" items={copy.scope.items} description={copy.scope.intro} label={copy.scope.title}/><ol>{copy.scope.items.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span>{item}</li>)}</ol></div></div></section>
    <section className="billing-section" id="subscription-cadence"><div className="page-frame billing-grid"><PricingSolid shape="d12" items={copy.billing.items.map(item=>item[0])} descriptions={copy.billing.items.map(item=>item[1])} description={copy.billing.body} label={copy.billing.objectLabel}/><div><span className="mono-label">{copy.billing.label}</span><h2>{copy.billing.title}</h2><p>{copy.billing.body}</p></div></div></section>
    <section className="pricing-review"><div className="page-frame"><div className="pricing-section-heading"><span className="mono-label">{copy.review.label}</span><div><h2>{copy.review.title}</h2><p>{copy.review.body}</p></div></div><div className="review-grid">{copy.review.items.map(([title,body],index)=><article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>
    <PricingFaq label={copy.faq.label} title={copy.faq.title} faceIntro={locale === "ro" ? "Această față identifică o decizie comercială de clarificat înainte de confirmarea scopului tehnic și a prețului. Subiect" : locale === "de" ? "Diese Fläche markiert eine kaufmännische Entscheidung, die vor Bestätigung von technischem Umfang und Preis geklärt werden sollte. Prüfthema" : "This face identifies a commercial decision to resolve before technical scope and pricing are confirmed. Review topic"} items={copy.faq.items}/>
    <section className="pricing-cta"><div className="pricing-cta-lines" aria-hidden="true"><i/><i/><i/></div><div className="page-frame"><span className="mono-label">{copy.cta.label}</span><h2>{copy.cta.titleA}<br/><em>{copy.cta.titleB}</em></h2><p>{copy.cta.body}</p><a className="project-link" href={`${localizedPath(locale, "/contact")}?project=pricing`}><span>{copy.cta.action}</span><b>↗</b></a></div></section>
    <SiteFooter locale={locale}/>
  </main>;
}
